// AUTO-GENERATED by docs/visual-guide/gen-app-data.mjs — do not edit by hand.
// Content dataset for the in-app visual guide (Arabic-first, low-literacy audience).
// `en`/`titleEn` are optional English text; audio/video voiceovers stay Arabic-only.
import type { UserRole } from '@/types'

export interface GuideStep { icon: string; ar: string; en?: string; img?: string; vid?: string; aud?: string }
export interface GuideLesson {
  id: string; icon: string; title: string; titleEn?: string; minRole: UserRole
  steps: GuideStep[]; titleAud?: string; thumb?: string
}
export interface GuideCategory {
  id: string; icon: string; title: string; titleEn?: string; minRole: UserRole; lessons: GuideLesson[]
}

const ROLE_RANK: Record<UserRole, number> = { member: 0, group_leader: 1, ministry_leader: 2, super_admin: 3 }
export const canSee = (role: UserRole, minRole: UserRole) => ROLE_RANK[role] >= ROLE_RANK[minRole]

export const GUIDE: GuideCategory[] = [
  {
    "id": "welcome",
    "icon": "👋",
    "title": "أهلًا بيك",
    "minRole": "member",
    "titleEn": "Welcome",
    "lessons": [
      {
        "id": "1",
        "icon": "⛪",
        "title": "ما هي إكليسيا؟",
        "titleEn": "What is Ekklesia?",
        "minRole": "member",
        "steps": [
          {
            "icon": "👋",
            "ar": "دي الصفحة الرئيسية لتطبيق إكليسيا.",
            "en": "This is the Ekklesia home page.",
            "img": "/help-guide/s1-0.jpg",
            "aud": "/help-guide/a-s1-0.m4a"
          },
          {
            "icon": "📜",
            "ar": "انزل تحت تشوف كل حاجة التطبيق بيعملها.",
            "en": "Scroll down to see everything the app can do.",
            "img": "/help-guide/s1-1.jpg",
            "vid": "/help-guide/v-s1-1.mp4",
            "aud": "/help-guide/a-s1-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s1-title.m4a",
        "thumb": "/help-guide/s1-0.jpg"
      },
      {
        "id": "2",
        "icon": "👥",
        "title": "الأدوار الأربعة في التطبيق",
        "titleEn": "The Four Roles in the App",
        "minRole": "member",
        "steps": [
          {
            "icon": "🧑‍🤝‍🧑",
            "ar": "كل شخص له دور: عضو، أو قائد مجموعة، أو قائد خدمة، أو مشرف.",
            "en": "Every person has a role: member, group leader, ministry leader, or admin.",
            "img": "/help-guide/s2-0.jpg",
            "aud": "/help-guide/a-s2-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s2-title.m4a",
        "thumb": "/help-guide/s2-0.jpg"
      }
    ]
  },
  {
    "id": "start",
    "icon": "🚪",
    "title": "أول خطوة",
    "minRole": "member",
    "titleEn": "Getting Started",
    "lessons": [
      {
        "id": "3",
        "icon": "🏛️",
        "title": "تسجيل كنيستك (للرعاة)",
        "titleEn": "Registering Your Church (for Pastors)",
        "minRole": "member",
        "steps": [
          {
            "icon": "🚀",
            "ar": "اضغط زر \"هيا نبدأ\" علشان تبدأ تسجيل كنيستك.",
            "en": "Tap the \"Let's Go\" button to start registering your church.",
            "img": "/help-guide/s3-0.jpg",
            "vid": "/help-guide/v-s3-0.mp4",
            "aud": "/help-guide/a-s3-0.m4a"
          },
          {
            "icon": "✉️",
            "ar": "اكتب بريدك الإلكتروني هنا.",
            "en": "Type your email address here.",
            "img": "/help-guide/s3-1.jpg",
            "aud": "/help-guide/a-s3-1.m4a"
          },
          {
            "icon": "🔒",
            "ar": "اكتب كلمة سر جديدة، وبعدين اكتبها تاني للتأكيد.",
            "en": "Type a new password, then type it again to confirm.",
            "img": "/help-guide/s3-2.jpg",
            "aud": "/help-guide/a-s3-2.m4a"
          },
          {
            "icon": "🙍",
            "ar": "اكتب اسمك ورقم تليفونك علشان نتواصل معاك.",
            "en": "Type your name and phone number so we can contact you.",
            "img": "/help-guide/s3-3.jpg",
            "aud": "/help-guide/a-s3-3.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s3-title.m4a",
        "thumb": "/help-guide/s3-0.jpg"
      },
      {
        "id": "4",
        "icon": "📝",
        "title": "إنشاء حساب والانضمام لكنيستك",
        "titleEn": "Creating an Account and Joining Your Church",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔎",
            "ar": "اكتب اسم كنيستك في خانة البحث.",
            "en": "Type your church's name in the search box.",
            "img": "/help-guide/s4-0.jpg",
            "vid": "/help-guide/v-s4-0.mp4",
            "aud": "/help-guide/a-s4-0.m4a"
          },
          {
            "icon": "👆",
            "ar": "اختار كنيستك من القائمة اللي هتظهر.",
            "en": "Pick your church from the list that appears.",
            "img": "/help-guide/s4-1.jpg",
            "aud": "/help-guide/a-s4-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s4-title.m4a",
        "thumb": "/help-guide/s4-0.jpg"
      },
      {
        "id": "5",
        "icon": "🔑",
        "title": "تسجيل الدخول",
        "titleEn": "Signing In",
        "minRole": "member",
        "steps": [
          {
            "icon": "✉️",
            "ar": "اكتب بريدك الإلكتروني هنا.",
            "en": "Type your email address here.",
            "img": "/help-guide/s5-0.jpg",
            "vid": "/help-guide/v-s5-0.mp4",
            "aud": "/help-guide/a-s5-0.m4a"
          },
          {
            "icon": "🔒",
            "ar": "اكتب كلمة السر بتاعتك.",
            "en": "Type your password.",
            "img": "/help-guide/s5-1.jpg",
            "aud": "/help-guide/a-s5-1.m4a"
          },
          {
            "icon": "👆",
            "ar": "اضغط زر \"دخول\".",
            "en": "Tap the \"Sign In\" button.",
            "img": "/help-guide/s5-2.jpg",
            "vid": "/help-guide/v-s5-2.mp4",
            "aud": "/help-guide/a-s5-2.m4a"
          },
          {
            "icon": "🏠",
            "ar": "أهلًا بيك! دي صفحتك الرئيسية.",
            "en": "Welcome! This is your home page.",
            "img": "/help-guide/s5-3.jpg",
            "aud": "/help-guide/a-s5-3.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s5-title.m4a",
        "thumb": "/help-guide/s5-0.jpg"
      },
      {
        "id": "5b",
        "icon": "📱",
        "title": "الدخول برقم التليفون (واتساب)",
        "titleEn": "Signing In with Your Phone (WhatsApp)",
        "minRole": "member",
        "steps": [
          {
            "icon": "📲",
            "ar": "اضغط على تبويب \"الهاتف\".",
            "en": "Tap the \"Phone\" tab.",
            "img": "/help-guide/s5b-0.jpg",
            "vid": "/help-guide/v-s5b-0.mp4",
            "aud": "/help-guide/a-s5b-0.m4a"
          },
          {
            "icon": "☎️",
            "ar": "اكتب رقم تليفونك بكود الدولة، زي +20 لمصر.",
            "en": "Type your phone number with the country code, like +20 for Egypt.",
            "img": "/help-guide/s5b-1.jpg",
            "aud": "/help-guide/a-s5b-1.m4a"
          },
          {
            "icon": "💬",
            "ar": "اضغط الزر ده، وهيوصلك كود من ٦ أرقام على واتساب.",
            "en": "Tap this button, and a 6-digit code will arrive on WhatsApp.",
            "img": "/help-guide/s5b-2.jpg",
            "aud": "/help-guide/a-s5b-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s5b-title.m4a",
        "thumb": "/help-guide/s5b-0.jpg"
      },
      {
        "id": "6",
        "icon": "🆘",
        "title": "نسيت كلمة السر؟",
        "titleEn": "Forgot Your Password?",
        "minRole": "member",
        "steps": [
          {
            "icon": "👆",
            "ar": "اضغط على \"هل نسيت كلمة المرور؟\".",
            "en": "Tap \"Forgot password?\".",
            "img": "/help-guide/s6-0.jpg",
            "vid": "/help-guide/v-s6-0.mp4",
            "aud": "/help-guide/a-s6-0.m4a"
          },
          {
            "icon": "✉️",
            "ar": "اكتب بريدك الإلكتروني.",
            "en": "Type your email address.",
            "img": "/help-guide/s6-1.jpg",
            "aud": "/help-guide/a-s6-1.m4a"
          },
          {
            "icon": "📨",
            "ar": "اضغط \"إرسال رابط إعادة التعيين\" وافتح بريدك بعدها.",
            "en": "Tap \"Send reset link\", then open your email.",
            "img": "/help-guide/s6-2.jpg",
            "vid": "/help-guide/v-s6-2.mp4",
            "aud": "/help-guide/a-s6-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s6-title.m4a",
        "thumb": "/help-guide/s6-0.jpg"
      },
      {
        "id": "7",
        "icon": "🪪",
        "title": "إكمال ملفك أول مرة",
        "titleEn": "Completing Your Profile the First Time",
        "minRole": "member",
        "steps": [
          {
            "icon": "🖊️",
            "ar": "أول مرة تدخل، هتكتب اسمك بالعربي ورقم تليفونك هنا.",
            "en": "The first time you sign in, you'll type your Arabic name and phone number here.",
            "img": "/help-guide/s7-0.jpg",
            "aud": "/help-guide/a-s7-0.m4a"
          },
          {
            "icon": "🔔",
            "ar": "اختار طريقة الإشعارات اللي تناسبك، وبعدين اضغط حفظ.",
            "en": "Choose the notification method you prefer, then tap Save.",
            "img": "/help-guide/s7-1.jpg",
            "aud": "/help-guide/a-s7-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s7-title.m4a",
        "thumb": "/help-guide/s7-0.jpg"
      },
      {
        "id": "8",
        "icon": "🧭",
        "title": "التنقل داخل التطبيق",
        "titleEn": "Getting Around the App",
        "minRole": "member",
        "steps": [
          {
            "icon": "📋",
            "ar": "القائمة الجانبية دي فيها كل صفحات التطبيق.",
            "en": "This side menu has every page in the app.",
            "img": "/help-guide/s8-0.jpg",
            "vid": "/help-guide/v-s8-0.mp4",
            "aud": "/help-guide/a-s8-0.m4a"
          },
          {
            "icon": "🔔",
            "ar": "الجرس ده بيوريك الإشعارات الجديدة.",
            "en": "This bell shows your new notifications.",
            "img": "/help-guide/s8-1.jpg",
            "aud": "/help-guide/a-s8-1.m4a"
          },
          {
            "icon": "🚪",
            "ar": "ومن هنا تقدر تسجل الخروج.",
            "en": "And from here you can sign out.",
            "img": "/help-guide/s8-2.jpg",
            "aud": "/help-guide/a-s8-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s8-title.m4a",
        "thumb": "/help-guide/s8-0.jpg"
      },
      {
        "id": "9",
        "icon": "🌐",
        "title": "التبديل بين العربية والإنجليزية",
        "titleEn": "Switching Between Arabic and English",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔤",
            "ar": "اضغط على زر اللغة اللي فوق علشان تبدّل بين العربي والإنجليزي.",
            "en": "Tap the language button at the top to switch between Arabic and English.",
            "img": "/help-guide/s9-0.jpg",
            "vid": "/help-guide/v-s9-0.mp4",
            "aud": "/help-guide/a-s9-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s9-title.m4a",
        "thumb": "/help-guide/s9-0.jpg"
      },
      {
        "id": "10",
        "icon": "🔕",
        "title": "تفعيل الإشعارات",
        "titleEn": "Turning On Notifications",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔔",
            "ar": "لما يظهرلك الكرت ده، اضغط \"تفعيل\" علشان توصلك الإشعارات على تليفونك.",
            "en": "When this card appears, tap \"Enable\" so notifications reach your phone.",
            "img": "/help-guide/s10-0.jpg",
            "aud": "/help-guide/a-s10-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s10-title.m4a",
        "thumb": "/help-guide/s10-0.jpg"
      },
      {
        "id": "11",
        "icon": "🏘️",
        "title": "أكثر من كنيسة بحساب واحد",
        "titleEn": "More Than One Church with One Account",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔁",
            "ar": "لو عندك أكتر من كنيسة، اضغط على اسم الكنيسة فوق علشان تبدّل بينهم.",
            "en": "If you belong to more than one church, tap the church name at the top to switch between them.",
            "img": "/help-guide/s11-0.jpg",
            "aud": "/help-guide/a-s11-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s11-title.m4a",
        "thumb": "/help-guide/s11-0.jpg"
      }
    ]
  },
  {
    "id": "member",
    "icon": "🏠",
    "title": "للأعضاء",
    "minRole": "member",
    "titleEn": "For Members",
    "lessons": [
      {
        "id": "12",
        "icon": "🏠",
        "title": "صفحتك الرئيسية",
        "titleEn": "Your Home Page",
        "minRole": "member",
        "steps": [
          {
            "icon": "📊",
            "ar": "هنا بتشوف حضورك ومجموعاتك وإشعاراتك.",
            "en": "Here you can see your attendance, your groups, and your notifications.",
            "img": "/help-guide/s12-0.jpg",
            "vid": "/help-guide/v-s12-0.mp4",
            "aud": "/help-guide/a-s12-0.m4a"
          },
          {
            "icon": "📅",
            "ar": "وتحت هتلاقي الفعاليات الجاية وآخر الإعلانات.",
            "en": "Below you'll find upcoming events and the latest announcements.",
            "img": "/help-guide/s12-1.jpg",
            "vid": "/help-guide/v-s12-1.mp4",
            "aud": "/help-guide/a-s12-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s12-title.m4a",
        "thumb": "/help-guide/s12-0.jpg"
      },
      {
        "id": "13",
        "icon": "🪪",
        "title": "ملفك الشخصي",
        "titleEn": "Your Profile",
        "minRole": "member",
        "steps": [
          {
            "icon": "👀",
            "ar": "ده ملفك الشخصي وفيه كل بياناتك.",
            "en": "This is your profile with all your details.",
            "img": "/help-guide/s13-0.jpg",
            "vid": "/help-guide/v-s13-0.mp4",
            "aud": "/help-guide/a-s13-0.m4a"
          },
          {
            "icon": "✏️",
            "ar": "اضغط زر التعديل علشان تغيّر بياناتك أو صورتك.",
            "en": "Tap the edit button to change your details or your photo.",
            "img": "/help-guide/s13-1.jpg",
            "vid": "/help-guide/v-s13-1.mp4",
            "aud": "/help-guide/a-s13-1.m4a"
          },
          {
            "icon": "📷",
            "ar": "من هنا تضيف أو تغيّر صورتك (أقصى حجم ٥ ميجا).",
            "en": "From here you can add or change your photo (5 MB max).",
            "img": "/help-guide/s13-2.jpg",
            "aud": "/help-guide/a-s13-2.m4a"
          },
          {
            "icon": "💾",
            "ar": "لما تخلص اضغط \"حفظ التغييرات\".",
            "en": "When you're done, tap \"Save Changes\".",
            "img": "/help-guide/s13-3.jpg",
            "aud": "/help-guide/a-s13-3.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s13-title.m4a",
        "thumb": "/help-guide/s13-0.jpg"
      },
      {
        "id": "14",
        "icon": "🔔",
        "title": "الإشعارات",
        "titleEn": "Notifications",
        "minRole": "member",
        "steps": [
          {
            "icon": "📬",
            "ar": "هنا كل إشعاراتك، والجديد عليه علامة.",
            "en": "Here are all your notifications — new ones are marked.",
            "img": "/help-guide/s14-0.jpg",
            "vid": "/help-guide/v-s14-0.mp4",
            "aud": "/help-guide/a-s14-0.m4a"
          },
          {
            "icon": "👆",
            "ar": "اضغط على أي إشعار علشان تشوف تفاصيله.",
            "en": "Tap any notification to see its details.",
            "img": "/help-guide/s14-1.jpg",
            "aud": "/help-guide/a-s14-1.m4a"
          },
          {
            "icon": "✅",
            "ar": "وزر \"تحديد الكل كمقروء\" بيمسح كل العلامات مرة واحدة.",
            "en": "The \"Mark all read\" button clears all the marks at once.",
            "img": "/help-guide/s14-2.jpg",
            "aud": "/help-guide/a-s14-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s14-title.m4a",
        "thumb": "/help-guide/s14-0.jpg"
      },
      {
        "id": "15",
        "icon": "📅",
        "title": "الفعاليات والتسجيل فيها",
        "titleEn": "Events and Registering for Them",
        "minRole": "member",
        "steps": [
          {
            "icon": "📋",
            "ar": "دي كل الفعاليات الجاية في كنيستك.",
            "en": "These are all the upcoming events at your church.",
            "img": "/help-guide/s15-0.jpg",
            "vid": "/help-guide/v-s15-0.mp4",
            "aud": "/help-guide/a-s15-0.m4a"
          },
          {
            "icon": "👆",
            "ar": "اضغط على أي فعالية تشوف تفاصيلها.",
            "en": "Tap any event to see its details.",
            "img": "/help-guide/s15-1.jpg",
            "vid": "/help-guide/v-s15-1.mp4",
            "aud": "/help-guide/a-s15-1.m4a"
          },
          {
            "icon": "✍️",
            "ar": "لو فيه زر \"تسجيل\"، اضغطه علشان تحجز مكانك.",
            "en": "If there's a \"Register\" button, tap it to save your spot.",
            "img": "/help-guide/s15-2.jpg",
            "aud": "/help-guide/a-s15-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s15-title.m4a",
        "thumb": "/help-guide/s15-0.jpg"
      },
      {
        "id": "16",
        "icon": "🤝",
        "title": "الخدمة والتطوع",
        "titleEn": "Serving and Volunteering",
        "minRole": "member",
        "steps": [
          {
            "icon": "📋",
            "ar": "دي أوقات الخدمة المتاحة للتطوع.",
            "en": "These are the serving times open for volunteers.",
            "img": "/help-guide/s16-0.jpg",
            "vid": "/help-guide/v-s16-0.mp4",
            "aud": "/help-guide/a-s16-0.m4a"
          },
          {
            "icon": "👆",
            "ar": "افتح أي وقت خدمة واضغط \"سجّل\" علشان تتطوع.",
            "en": "Open any serving time and tap \"Sign Up\" to volunteer.",
            "img": "/help-guide/s16-1.jpg",
            "vid": "/help-guide/v-s16-1.mp4",
            "aud": "/help-guide/a-s16-1.m4a"
          },
          {
            "icon": "✅",
            "ar": "اشتراكاتك بتظهر تحت في \"اشتراكاتي\".",
            "en": "Your signups appear below under \"My Signups\".",
            "img": "/help-guide/s16-2.jpg",
            "aud": "/help-guide/a-s16-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s16-title.m4a",
        "thumb": "/help-guide/s16-0.jpg"
      },
      {
        "id": "17",
        "icon": "📢",
        "title": "الإعلانات",
        "titleEn": "Announcements",
        "minRole": "member",
        "steps": [
          {
            "icon": "📰",
            "ar": "هنا آخر أخبار وإعلانات الكنيسة، والمثبّت بيظهر الأول.",
            "en": "Here is the latest church news and announcements — pinned ones show first.",
            "img": "/help-guide/s17-0.jpg",
            "vid": "/help-guide/v-s17-0.mp4",
            "aud": "/help-guide/a-s17-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s17-title.m4a",
        "thumb": "/help-guide/s17-0.jpg"
      },
      {
        "id": "18",
        "icon": "🙏",
        "title": "طلبات الصلاة",
        "titleEn": "Prayer Requests",
        "minRole": "member",
        "steps": [
          {
            "icon": "✍️",
            "ar": "اكتب طلب صلاتك هنا.",
            "en": "Type your prayer request here.",
            "img": "/help-guide/s18-0.jpg",
            "vid": "/help-guide/v-s18-0.mp4",
            "aud": "/help-guide/a-s18-0.m4a"
          },
          {
            "icon": "👁️",
            "ar": "اختار مين يشوف طلبك: الكل، أو من غير اسمك، أو القادة بس.",
            "en": "Choose who can see your request: everyone, anonymous, or leaders only.",
            "img": "/help-guide/s18-1.jpg",
            "aud": "/help-guide/a-s18-1.m4a"
          },
          {
            "icon": "📤",
            "ar": "اضغط \"إرسال الطلب\".",
            "en": "Tap \"Submit Prayer\".",
            "img": "/help-guide/s18-2.jpg",
            "vid": "/help-guide/v-s18-2.mp4",
            "aud": "/help-guide/a-s18-2.m4a"
          },
          {
            "icon": "❤️",
            "ar": "واضغط \"أصلي\" على طلبات غيرك علشان تشجعهم.",
            "en": "And tap \"I'm Praying\" on other people's requests to encourage them.",
            "img": "/help-guide/s18-3.jpg",
            "vid": "/help-guide/v-s18-3.mp4",
            "aud": "/help-guide/a-s18-3.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s18-title.m4a",
        "thumb": "/help-guide/s18-0.jpg"
      },
      {
        "id": "19",
        "icon": "📖",
        "title": "قراءة الكتاب المقدس",
        "titleEn": "Reading the Bible",
        "minRole": "member",
        "steps": [
          {
            "icon": "📚",
            "ar": "اضغط \"اختر سفرًا\" واختار السفر اللي عايز تقراه.",
            "en": "Tap \"Select a Book\" and choose the book you want to read.",
            "img": "/help-guide/s19-0.jpg",
            "vid": "/help-guide/v-s19-0.mp4",
            "aud": "/help-guide/a-s19-0.m4a"
          },
          {
            "icon": "🔢",
            "ar": "وبعدين اختار الإصحاح.",
            "en": "Then choose the chapter.",
            "img": "/help-guide/s19-1.jpg",
            "vid": "/help-guide/v-s19-1.mp4",
            "aud": "/help-guide/a-s19-1.m4a"
          },
          {
            "icon": "🖍️",
            "ar": "اضغط على أي آية علشان تظللها أو تحفظها أو تنسخها.",
            "en": "Tap any verse to highlight it, save it, or copy it.",
            "img": "/help-guide/s19-2.jpg",
            "vid": "/help-guide/v-s19-2.mp4",
            "aud": "/help-guide/a-s19-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s19-title.m4a",
        "thumb": "/help-guide/s19-0.jpg"
      },
      {
        "id": "20",
        "icon": "⛪",
        "title": "الأجبية والقراءات والألحان",
        "titleEn": "Agpeya, Readings, and Hymns",
        "minRole": "member",
        "steps": [
          {
            "icon": "🕐",
            "ar": "من هنا تفتح الأجبية وقراءات اليوم والقداسات والألحان.",
            "en": "From here you can open the Agpeya, today's readings, liturgies, and hymns.",
            "img": "/help-guide/s20-0.jpg",
            "vid": "/help-guide/v-s20-0.mp4",
            "aud": "/help-guide/a-s20-0.m4a"
          },
          {
            "icon": "📿",
            "ar": "مثلًا اضغط \"الأجبية\" واختار الساعة اللي عايز تصليها.",
            "en": "For example, tap \"Agpeya\" and choose the hour you want to pray.",
            "img": "/help-guide/s20-1.jpg",
            "vid": "/help-guide/v-s20-1.mp4",
            "aud": "/help-guide/a-s20-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s20-title.m4a",
        "thumb": "/help-guide/s20-0.jpg"
      },
      {
        "id": "21",
        "icon": "🎵",
        "title": "الترانيم",
        "titleEn": "Songs",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔎",
            "ar": "دوّر على أي ترنيمة بالاسم أو بكلماتها.",
            "en": "Search for any song by its name or its lyrics.",
            "img": "/help-guide/s21-0.jpg",
            "vid": "/help-guide/v-s21-0.mp4",
            "aud": "/help-guide/a-s21-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s21-title.m4a",
        "thumb": "/help-guide/s21-0.jpg"
      },
      {
        "id": "22",
        "icon": "🚪",
        "title": "حجز قاعة",
        "titleEn": "Booking a Room",
        "minRole": "member",
        "steps": [
          {
            "icon": "🏢",
            "ar": "اختار القاعة واليوم، وشوف المواعيد الفاضية.",
            "en": "Choose the room and the day, and see the free time slots.",
            "img": "/help-guide/s22-0.jpg",
            "vid": "/help-guide/v-s22-0.mp4",
            "aud": "/help-guide/a-s22-0.m4a"
          },
          {
            "icon": "➕",
            "ar": "اضغط زر الحجز واكتب عنوان ووقت حجزك.",
            "en": "Tap the booking button and enter a title and time for your booking.",
            "img": "/help-guide/s22-1.jpg",
            "vid": "/help-guide/v-s22-1.mp4",
            "aud": "/help-guide/a-s22-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s22-title.m4a",
        "thumb": "/help-guide/s22-0.jpg"
      },
      {
        "id": "23",
        "icon": "🤲",
        "title": "احتياجات الكنائس",
        "titleEn": "Church Needs",
        "minRole": "member",
        "steps": [
          {
            "icon": "📋",
            "ar": "هنا كنائس تانية بتطلب مساعدة، وتقدر تساعدهم.",
            "en": "Here, other churches are asking for help — and you can help them.",
            "img": "/help-guide/s23-0.jpg",
            "vid": "/help-guide/v-s23-0.mp4",
            "aud": "/help-guide/a-s23-0.m4a"
          },
          {
            "icon": "💌",
            "ar": "افتح أي احتياج واضغط \"قدّم مساعدة\" واكتب رسالتك.",
            "en": "Open any need, tap the offer-help button, and write your message.",
            "img": "/help-guide/s23-1.jpg",
            "aud": "/help-guide/a-s23-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s23-title.m4a",
        "thumb": "/help-guide/s23-0.jpg"
      },
      {
        "id": "24",
        "icon": "👨‍👩‍👧",
        "title": "المجموعات والانضمام ليها",
        "titleEn": "Groups and How to Join Them",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔎",
            "ar": "من صفحة المجموعات تشوف مجموعاتك والمجموعات المفتوحة.",
            "en": "From the groups page you can see your groups and the open ones.",
            "img": "/help-guide/s24-0.jpg",
            "aud": "/help-guide/a-s24-0.m4a"
          },
          {
            "icon": "✋",
            "ar": "اضغط \"اطلب الانضمام\" والقائد هيوافق عليك.",
            "en": "Tap \"Request to Join\" and the leader will approve you.",
            "img": "/help-guide/s24-1.jpg",
            "aud": "/help-guide/a-s24-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s24-title.m4a",
        "thumb": "/help-guide/s24-0.jpg"
      },
      {
        "id": "25",
        "icon": "💌",
        "title": "دعوات الكنائس",
        "titleEn": "Church Invitations",
        "minRole": "member",
        "steps": [
          {
            "icon": "✅",
            "ar": "لو كنيسة دعتك، هيظهر كرت على صفحتك: اقبل أو ارفض.",
            "en": "If a church invited you, a card will appear on your home page: accept or decline.",
            "img": "/help-guide/s25-0.jpg",
            "aud": "/help-guide/a-s25-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s25-title.m4a",
        "thumb": "/help-guide/s25-0.jpg"
      }
    ]
  },
  {
    "id": "leader",
    "icon": "👨‍👩‍👧‍👦",
    "title": "لقائد المجموعة",
    "minRole": "group_leader",
    "titleEn": "For Group Leaders",
    "lessons": [
      {
        "id": "26",
        "icon": "👨‍👩‍👧‍👦",
        "title": "صفحة مجموعتي (للقائد)",
        "titleEn": "My Group Page (for Leaders)",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "📊",
            "ar": "دي صفحة مجموعتك: الأعضاء والحضور والاجتماعات.",
            "en": "This is your group's page: members, attendance, and gatherings.",
            "img": "/help-guide/s26-0.jpg",
            "vid": "/help-guide/v-s26-0.mp4",
            "aud": "/help-guide/a-s26-0.m4a"
          },
          {
            "icon": "⚠️",
            "ar": "وهنا الأعضاء اللي غابوا كتير ومحتاجين افتقاد.",
            "en": "And here are the members who have missed a lot and need a follow-up visit.",
            "img": "/help-guide/s26-1.jpg",
            "aud": "/help-guide/a-s26-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s26-title.m4a",
        "thumb": "/help-guide/s26-0.jpg"
      },
      {
        "id": "27",
        "icon": "🗓️",
        "title": "إنشاء اجتماع جديد",
        "titleEn": "Creating a New Gathering",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "🕐",
            "ar": "حدد يوم وساعة الاجتماع.",
            "en": "Set the day and time of the gathering.",
            "img": "/help-guide/s27-0.jpg",
            "vid": "/help-guide/v-s27-0.mp4",
            "aud": "/help-guide/a-s27-0.m4a"
          },
          {
            "icon": "📝",
            "ar": "اكتب موضوع الاجتماع ومكانه.",
            "en": "Type the gathering's topic and location.",
            "img": "/help-guide/s27-1.jpg",
            "vid": "/help-guide/v-s27-1.mp4",
            "aud": "/help-guide/a-s27-1.m4a"
          },
          {
            "icon": "✅",
            "ar": "اضغط \"إنشاء الاجتماع\".",
            "en": "Tap \"Create Gathering\".",
            "img": "/help-guide/s27-2.jpg",
            "vid": "/help-guide/v-s27-2.mp4",
            "aud": "/help-guide/a-s27-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s27-title.m4a",
        "thumb": "/help-guide/s27-0.jpg"
      },
      {
        "id": "28",
        "icon": "✅",
        "title": "تسجيل الحضور",
        "titleEn": "Taking Attendance",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "👆",
            "ar": "اضغط على اسم أي عضو علشان تغيّر حالته: حاضر، متأخر، غايب.",
            "en": "Tap any member's name to change their status: present, late, or absent.",
            "img": "/help-guide/s28-0.jpg",
            "vid": "/help-guide/v-s28-0.mp4",
            "aud": "/help-guide/a-s28-0.m4a"
          },
          {
            "icon": "💾",
            "ar": "اضغط \"حفظ الحضور\" في أي وقت.",
            "en": "Tap \"Save Attendance\" at any time.",
            "img": "/help-guide/s28-1.jpg",
            "vid": "/help-guide/v-s28-1.mp4",
            "aud": "/help-guide/a-s28-1.m4a"
          },
          {
            "icon": "🏁",
            "ar": "ولما الاجتماع يخلص، اضغط \"إنهاء الاجتماع\".",
            "en": "And when the gathering ends, tap \"Complete Gathering\".",
            "img": "/help-guide/s28-2.jpg",
            "vid": "/help-guide/v-s28-2.mp4",
            "aud": "/help-guide/a-s28-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s28-title.m4a",
        "thumb": "/help-guide/s28-0.jpg"
      },
      {
        "id": "29",
        "icon": "🙏",
        "title": "صلوات المجموعة وتسجيل الاستجابات",
        "titleEn": "Group Prayers and Recording Answers",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "➕",
            "ar": "من قسم الصلاة اضغط \"أضف طلبًا\" واكتب الطلب.",
            "en": "From the prayer section, tap \"Add Request\" and write the request.",
            "img": "/help-guide/s29-0.jpg",
            "aud": "/help-guide/a-s29-0.m4a"
          },
          {
            "icon": "🎉",
            "ar": "ولما ربنا يستجيب، اضغط \"سجّل الاستجابة\".",
            "en": "And when God answers, tap the record-answer button.",
            "img": "/help-guide/s29-1.jpg",
            "aud": "/help-guide/a-s29-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s29-title.m4a",
        "thumb": "/help-guide/s29-0.jpg"
      },
      {
        "id": "30",
        "icon": "✋",
        "title": "الموافقة على طلبات الانضمام للمجموعة",
        "titleEn": "Approving Group Join Requests",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "✅",
            "ar": "طلبات الانضمام بتظهر في صفحة مجموعتك: اضغط \"موافقة\" أو \"رفض\".",
            "en": "Join requests appear on your group's page: tap \"Approve\" or \"Decline\".",
            "img": "/help-guide/s30-0.jpg",
            "aud": "/help-guide/a-s30-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s30-title.m4a",
        "thumb": "/help-guide/s30-0.jpg"
      },
      {
        "id": "31",
        "icon": "📞",
        "title": "الزوار المسندين ليك",
        "titleEn": "Visitors Assigned to You",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "دول الزوار اللي الكنيسة كلفتك تتابعهم.",
            "en": "These are the visitors the church asked you to follow up with.",
            "img": "/help-guide/s31-0.jpg",
            "vid": "/help-guide/v-s31-0.mp4",
            "aud": "/help-guide/a-s31-0.m4a"
          },
          {
            "icon": "📞",
            "ar": "اتصل بيهم، وبعدين اضغط \"سجّل تواصل\" واكتب اللي حصل.",
            "en": "Call them, then tap \"Log Contact\" and write what happened.",
            "img": "/help-guide/s31-1.jpg",
            "vid": "/help-guide/v-s31-1.mp4",
            "aud": "/help-guide/a-s31-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s31-title.m4a",
        "thumb": "/help-guide/s31-0.jpg"
      }
    ]
  },
  {
    "id": "admin",
    "icon": "🛠️",
    "title": "للمشرفين والقادة",
    "minRole": "ministry_leader",
    "titleEn": "For Admins & Leaders",
    "lessons": [
      {
        "id": "32",
        "icon": "📊",
        "title": "لوحة تحكم المشرف",
        "titleEn": "The Admin Dashboard",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📈",
            "ar": "دي صحة كنيستك كلها في صفحة واحدة: الأعضاء والزوار والحضور.",
            "en": "This is your whole church's health on one page: members, visitors, and attendance.",
            "img": "/help-guide/s32-0.jpg",
            "vid": "/help-guide/v-s32-0.mp4",
            "aud": "/help-guide/a-s32-0.m4a"
          },
          {
            "icon": "⚠️",
            "ar": "قسم \"يحتاج انتباه\" بيوريك اللي لازم تتابعه النهارده.",
            "en": "The \"Needs Attention\" section shows you what to follow up on today.",
            "img": "/help-guide/s32-1.jpg",
            "aud": "/help-guide/a-s32-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s32-title.m4a",
        "thumb": "/help-guide/s32-0.jpg"
      },
      {
        "id": "33",
        "icon": "📇",
        "title": "دليل الأعضاء",
        "titleEn": "The Member Directory",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "ده دليل كل أعضاء الكنيسة.",
            "en": "This is the directory of every church member.",
            "img": "/help-guide/s33-0.jpg",
            "vid": "/help-guide/v-s33-0.mp4",
            "aud": "/help-guide/a-s33-0.m4a"
          },
          {
            "icon": "🔎",
            "ar": "اكتب أي اسم في البحث والنتايج هتظهر فورًا.",
            "en": "Type any name in the search and results appear instantly.",
            "img": "/help-guide/s33-1.jpg",
            "vid": "/help-guide/v-s33-1.mp4",
            "aud": "/help-guide/a-s33-1.m4a"
          },
          {
            "icon": "👆",
            "ar": "اضغط على أي عضو تفتح ملفه.",
            "en": "Tap any member to open their profile.",
            "img": "/help-guide/s33-2.jpg",
            "vid": "/help-guide/v-s33-2.mp4",
            "aud": "/help-guide/a-s33-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s33-title.m4a",
        "thumb": "/help-guide/s33-0.jpg"
      },
      {
        "id": "34",
        "icon": "➕",
        "title": "إضافة عضو جديد",
        "titleEn": "Adding a New Member",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "👆",
            "ar": "اضغط زر \"إضافة عضو\".",
            "en": "Tap the \"Add member\" button.",
            "img": "/help-guide/s34-0.jpg",
            "vid": "/help-guide/v-s34-0.mp4",
            "aud": "/help-guide/a-s34-0.m4a"
          },
          {
            "icon": "🖊️",
            "ar": "اكتب اسمه ورقم تليفونه.",
            "en": "Type their name and phone number.",
            "img": "/help-guide/s34-1.jpg",
            "aud": "/help-guide/a-s34-1.m4a"
          },
          {
            "icon": "✅",
            "ar": "اضغط \"إضافة عضو\" — وهو هيقدر يدخل بالواتساب على طول.",
            "en": "Tap \"Add member\" — and they'll be able to sign in with WhatsApp right away.",
            "img": "/help-guide/s34-2.jpg",
            "vid": "/help-guide/v-s34-2.mp4",
            "aud": "/help-guide/a-s34-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s34-title.m4a",
        "thumb": "/help-guide/s34-0.jpg"
      },
      {
        "id": "35",
        "icon": "🗂️",
        "title": "إدارة ملف عضو",
        "titleEn": "Managing a Member's Profile",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📑",
            "ar": "ملف العضو فيه بياناته ومحطاته الروحية ومشاركاته.",
            "en": "A member's profile has their details, spiritual milestones, and involvement.",
            "img": "/help-guide/s35-0.jpg",
            "vid": "/help-guide/v-s35-0.mp4",
            "aud": "/help-guide/a-s35-0.m4a"
          },
          {
            "icon": "⚙️",
            "ar": "من تبويب \"إدارة\" تقدر تغيّر دوره وصلاحياته.",
            "en": "From the \"Manage\" tab you can change their role and permissions.",
            "img": "/help-guide/s35-1.jpg",
            "vid": "/help-guide/v-s35-1.mp4",
            "aud": "/help-guide/a-s35-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s35-title.m4a",
        "thumb": "/help-guide/s35-0.jpg"
      },
      {
        "id": "36",
        "icon": "🚶",
        "title": "قائمة الزوار ومتابعتهم",
        "titleEn": "The Visitor List and Follow-Up",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "كل زائر جديد بيظهر هنا، والمتأخر عليه تنبيه أحمر.",
            "en": "Every new visitor appears here, and overdue ones get a red alert.",
            "img": "/help-guide/s36-0.jpg",
            "vid": "/help-guide/v-s36-0.mp4",
            "aud": "/help-guide/a-s36-0.m4a"
          },
          {
            "icon": "🤝",
            "ar": "اضغط \"إسناد\" واختار قائد يتابع الزائر.",
            "en": "Tap \"Assign\" and choose a leader to follow up with the visitor.",
            "img": "/help-guide/s36-1.jpg",
            "vid": "/help-guide/v-s36-1.mp4",
            "aud": "/help-guide/a-s36-1.m4a"
          },
          {
            "icon": "🎉",
            "ar": "ولما يبقى جاهز، اضغط \"تحويل لعضو\".",
            "en": "And when they're ready, tap \"Convert to Member\".",
            "img": "/help-guide/s36-2.jpg",
            "aud": "/help-guide/a-s36-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s36-title.m4a",
        "thumb": "/help-guide/s36-0.jpg"
      },
      {
        "id": "37",
        "icon": "📱",
        "title": "كود QR للزوار",
        "titleEn": "The Visitor QR Code",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "🖨️",
            "ar": "اطبع الكود ده وحطه على باب الكنيسة.",
            "en": "Print this code and put it at the church entrance.",
            "img": "/help-guide/s37-0.jpg",
            "vid": "/help-guide/v-s37-0.mp4",
            "aud": "/help-guide/a-s37-0.m4a"
          },
          {
            "icon": "⬇️",
            "ar": "زر \"تحميل PNG\" بينزّل الصورة للطباعة.",
            "en": "The \"Download PNG\" button downloads the image for printing.",
            "img": "/help-guide/s37-1.jpg",
            "aud": "/help-guide/a-s37-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s37-title.m4a",
        "thumb": "/help-guide/s37-0.jpg"
      },
      {
        "id": "38",
        "icon": "👨‍👩‍👧‍👦",
        "title": "إدارة المجموعات",
        "titleEn": "Managing Groups",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "دي كل مجموعات الكنيسة.",
            "en": "These are all the church's groups.",
            "img": "/help-guide/s38-0.jpg",
            "vid": "/help-guide/v-s38-0.mp4",
            "aud": "/help-guide/a-s38-0.m4a"
          },
          {
            "icon": "➕",
            "ar": "اضغط \"مجموعة جديدة\" علشان تنشئ واحدة.",
            "en": "Tap \"New Group\" to create one.",
            "img": "/help-guide/s38-1.jpg",
            "vid": "/help-guide/v-s38-1.mp4",
            "aud": "/help-guide/a-s38-1.m4a"
          },
          {
            "icon": "🖊️",
            "ar": "اكتب اسم المجموعة واختار القائد ويوم الاجتماع.",
            "en": "Type the group's name and choose the leader and meeting day.",
            "img": "/help-guide/s38-2.jpg",
            "aud": "/help-guide/a-s38-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s38-title.m4a",
        "thumb": "/help-guide/s38-0.jpg"
      },
      {
        "id": "39",
        "icon": "🛠️",
        "title": "إدارة الخدمات (الوزارات)",
        "titleEn": "Managing Ministries",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "دي كل خدمات الكنيسة، واضغط على أي خدمة تشوف فريقها.",
            "en": "These are all the church's ministries — tap any one to see its team.",
            "img": "/help-guide/s39-0.jpg",
            "vid": "/help-guide/v-s39-0.mp4",
            "aud": "/help-guide/a-s39-0.m4a"
          },
          {
            "icon": "➕",
            "ar": "زر \"إضافة خدمة\" بينشئ خدمة جديدة باسم وقائد.",
            "en": "The add-ministry button creates a new ministry with a name and a leader.",
            "img": "/help-guide/s39-1.jpg",
            "aud": "/help-guide/a-s39-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s39-title.m4a",
        "thumb": "/help-guide/s39-0.jpg"
      },
      {
        "id": "40",
        "icon": "🎪",
        "title": "إنشاء فعالية (٧ خطوات)",
        "titleEn": "Creating an Event (7 Steps)",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "🖊️",
            "ar": "الخطوة ١: اكتب اسم الفعالية واختار نوعها.",
            "en": "Step 1: type the event's name and choose its type.",
            "img": "/help-guide/s40-0.jpg",
            "vid": "/help-guide/v-s40-0.mp4",
            "aud": "/help-guide/a-s40-0.m4a"
          },
          {
            "icon": "🕐",
            "ar": "الخطوة ٢: حدد التاريخ والساعة.",
            "en": "Step 2: set the date and time.",
            "img": "/help-guide/s40-1.jpg",
            "vid": "/help-guide/v-s40-1.mp4",
            "aud": "/help-guide/a-s40-1.m4a"
          },
          {
            "icon": "📍",
            "ar": "الخطوة ٣: اكتب المكان.",
            "en": "Step 3: type the location.",
            "img": "/help-guide/s40-2.jpg",
            "vid": "/help-guide/v-s40-2.mp4",
            "aud": "/help-guide/a-s40-2.m4a"
          },
          {
            "icon": "⚙️",
            "ar": "الخطوة ٤: فعّل \"التسجيل مطلوب\" لو عايز الناس تحجز.",
            "en": "Step 4: turn on \"Registration required\" if you want people to reserve a spot.",
            "img": "/help-guide/s40-3.jpg",
            "vid": "/help-guide/v-s40-3.mp4",
            "aud": "/help-guide/a-s40-3.m4a"
          },
          {
            "icon": "👥",
            "ar": "الخطوة ٥: اختار مين يشوف الفعالية.",
            "en": "Step 5: choose who can see the event.",
            "img": "/help-guide/s40-4.jpg",
            "vid": "/help-guide/v-s40-4.mp4",
            "aud": "/help-guide/a-s40-4.m4a"
          },
          {
            "icon": "🤝",
            "ar": "الخطوة ٦: اطلب فرق خدمة لو محتاج متطوعين.",
            "en": "Step 6: request serving teams if you need volunteers.",
            "img": "/help-guide/s40-5.jpg",
            "vid": "/help-guide/v-s40-5.mp4",
            "aud": "/help-guide/a-s40-5.m4a"
          },
          {
            "icon": "✅",
            "ar": "الخطوة ٧: راجع كل حاجة واضغط \"إنشاء الفعالية\".",
            "en": "Step 7: review everything and tap \"Create Event\".",
            "img": "/help-guide/s40-6.jpg",
            "vid": "/help-guide/v-s40-6.mp4",
            "aud": "/help-guide/a-s40-6.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s40-title.m4a",
        "thumb": "/help-guide/s40-0.jpg"
      },
      {
        "id": "41",
        "icon": "📋",
        "title": "قوالب الفعاليات",
        "titleEn": "Event Templates",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "♻️",
            "ar": "اعمل قالب لقداس الأحد مرة واحدة، واستخدمه كل أسبوع.",
            "en": "Make a template for Sunday service once, and use it every week.",
            "img": "/help-guide/s41-0.jpg",
            "vid": "/help-guide/v-s41-0.mp4",
            "aud": "/help-guide/a-s41-0.m4a"
          },
          {
            "icon": "▶️",
            "ar": "من صفحة الفعاليات اضغط \"من قالب\" وهيتعبى كل حاجة لوحده.",
            "en": "From the events page tap \"From Template\" and everything fills in by itself.",
            "img": "/help-guide/s41-1.jpg",
            "aud": "/help-guide/a-s41-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s41-title.m4a",
        "thumb": "/help-guide/s41-0.jpg"
      },
      {
        "id": "42",
        "icon": "🗓️",
        "title": "تقويم الكنيسة",
        "titleEn": "The Church Calendar",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📅",
            "ar": "كل الفعاليات والخدمة والاجتماعات في تقويم واحد ملوّن.",
            "en": "All events, serving, and gatherings in one color-coded calendar.",
            "img": "/help-guide/s42-0.jpg",
            "vid": "/help-guide/v-s42-0.mp4",
            "aud": "/help-guide/a-s42-0.m4a"
          },
          {
            "icon": "🎚️",
            "ar": "الأزرار دي بتظهر وتخفي كل نوع.",
            "en": "These buttons show and hide each type.",
            "img": "/help-guide/s42-1.jpg",
            "aud": "/help-guide/a-s42-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s42-title.m4a",
        "thumb": "/help-guide/s42-0.jpg"
      },
      {
        "id": "43",
        "icon": "🧹",
        "title": "إدارة أماكن وأوقات الخدمة",
        "titleEn": "Managing Serving Areas and Slots",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "من تبويب \"أماكن الخدمة\" اعمل فرق زي الاستقبال والصوت.",
            "en": "From the \"Serving Areas\" tab, create teams like welcome and sound.",
            "img": "/help-guide/s43-0.jpg",
            "vid": "/help-guide/v-s43-0.mp4",
            "aud": "/help-guide/a-s43-0.m4a"
          },
          {
            "icon": "🕐",
            "ar": "ومن \"أوقات الخدمة\" حدد المواعيد اللي الناس تسجل فيها.",
            "en": "And from \"Serving Slots\", set the times people can sign up for.",
            "img": "/help-guide/s43-1.jpg",
            "vid": "/help-guide/v-s43-1.mp4",
            "aud": "/help-guide/a-s43-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s43-title.m4a",
        "thumb": "/help-guide/s43-0.jpg"
      },
      {
        "id": "44",
        "icon": "📢",
        "title": "إدارة الإعلانات",
        "titleEn": "Managing Announcements",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "➕",
            "ar": "اضغط \"إعلان جديد\".",
            "en": "Tap \"New Announcement\".",
            "img": "/help-guide/s44-0.jpg",
            "vid": "/help-guide/v-s44-0.mp4",
            "aud": "/help-guide/a-s44-0.m4a"
          },
          {
            "icon": "🖊️",
            "ar": "اكتب العنوان والمحتوى.",
            "en": "Type the title and the content.",
            "img": "/help-guide/s44-1.jpg",
            "aud": "/help-guide/a-s44-1.m4a"
          },
          {
            "icon": "📌",
            "ar": "فعّل \"تثبيت\" للإعلانات المهمة، وبعدين انشر.",
            "en": "Turn on \"Pinned\" for important announcements, then publish.",
            "img": "/help-guide/s44-2.jpg",
            "vid": "/help-guide/v-s44-2.mp4",
            "aud": "/help-guide/a-s44-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s44-title.m4a",
        "thumb": "/help-guide/s44-0.jpg"
      },
      {
        "id": "45",
        "icon": "🙏",
        "title": "إدارة طلبات الصلاة",
        "titleEn": "Managing Prayer Requests",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "كل طلبات الصلاة هنا: نشطة، ومستجابة، ومؤرشفة.",
            "en": "All prayer requests are here: active, answered, and archived.",
            "img": "/help-guide/s45-0.jpg",
            "vid": "/help-guide/v-s45-0.mp4",
            "aud": "/help-guide/a-s45-0.m4a"
          },
          {
            "icon": "🤝",
            "ar": "زر \"إسناد\" بيخلّي حد معيّن يصلي ويتابع الطلب.",
            "en": "The \"Assign\" button lets a specific person pray and follow up on the request.",
            "img": "/help-guide/s45-1.jpg",
            "aud": "/help-guide/a-s45-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s45-title.m4a",
        "thumb": "/help-guide/s45-0.jpg"
      },
      {
        "id": "46",
        "icon": "🎵",
        "title": "إدارة الترانيم والعرض",
        "titleEn": "Managing Songs and the Presenter",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "➕",
            "ar": "زر \"إضافة ترنيمة\": الاسم، الكلمات، وسطر فاضي بين كل شريحة.",
            "en": "The \"Add Song\" button: name, lyrics, and a blank line between each slide.",
            "img": "/help-guide/s46-0.jpg",
            "vid": "/help-guide/v-s46-0.mp4",
            "aud": "/help-guide/a-s46-0.m4a"
          },
          {
            "icon": "📽️",
            "ar": "وزر \"عرض\" بيفتح شاشة العرض للبروجيكتور.",
            "en": "And the \"Present\" button opens the projector display.",
            "img": "/help-guide/s46-1.jpg",
            "aud": "/help-guide/a-s46-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s46-title.m4a",
        "thumb": "/help-guide/s46-0.jpg"
      },
      {
        "id": "47",
        "icon": "🏡",
        "title": "الافتقاد والزيارات",
        "titleEn": "Outreach and Visits",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "هنا بتتابع مين اتزار في بيته ومين محتاج زيارة.",
            "en": "Here you track who has been visited at home and who needs a visit.",
            "img": "/help-guide/s47-0.jpg",
            "vid": "/help-guide/v-s47-0.mp4",
            "aud": "/help-guide/a-s47-0.m4a"
          },
          {
            "icon": "📝",
            "ar": "بعد كل زيارة اضغط \"سجّل زيارة\" واكتب اللي حصل.",
            "en": "After every visit, tap \"Log Visit\" and write what happened.",
            "img": "/help-guide/s47-1.jpg",
            "aud": "/help-guide/a-s47-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s47-title.m4a",
        "thumb": "/help-guide/s47-0.jpg"
      },
      {
        "id": "48",
        "icon": "🏢",
        "title": "إدارة القاعات",
        "titleEn": "Managing Rooms",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "➕",
            "ar": "ضيف قاعات كنيستك علشان الناس تقدر تحجزها.",
            "en": "Add your church's rooms so people can book them.",
            "img": "/help-guide/s48-0.jpg",
            "vid": "/help-guide/v-s48-0.mp4",
            "aud": "/help-guide/a-s48-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s48-title.m4a",
        "thumb": "/help-guide/s48-0.jpg"
      },
      {
        "id": "49",
        "icon": "📣",
        "title": "إرسال إشعار لكل الكنيسة",
        "titleEn": "Sending a Notification to the Whole Church",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "🎯",
            "ar": "اختار مين يستلم: الكل، أو مجموعة، أو خدمة معينة.",
            "en": "Choose who receives it: everyone, a group, or a specific ministry.",
            "img": "/help-guide/s49-0.jpg",
            "vid": "/help-guide/v-s49-0.mp4",
            "aud": "/help-guide/a-s49-0.m4a"
          },
          {
            "icon": "🖊️",
            "ar": "اكتب العنوان والرسالة، وشوف عدد اللي هيوصلهم.",
            "en": "Type the title and the message, and see how many people it will reach.",
            "img": "/help-guide/s49-1.jpg",
            "aud": "/help-guide/a-s49-1.m4a"
          },
          {
            "icon": "📤",
            "ar": "اضغط \"إرسال الإشعار\" وأكّد.",
            "en": "Tap \"Send Notification\" and confirm.",
            "img": "/help-guide/s49-2.jpg",
            "aud": "/help-guide/a-s49-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s49-title.m4a",
        "thumb": "/help-guide/s49-0.jpg"
      },
      {
        "id": "50",
        "icon": "✋",
        "title": "الموافقة على طلبات الانضمام للكنيسة",
        "titleEn": "Approving Church Join Requests",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "✅",
            "ar": "اللي طلب ينضم لكنيستك بيظهر هنا: اضغط \"موافقة\" أو \"رفض\".",
            "en": "Anyone who asked to join your church appears here: tap \"Approve\" or \"Decline\".",
            "img": "/help-guide/s50-0.jpg",
            "vid": "/help-guide/v-s50-0.mp4",
            "aud": "/help-guide/a-s50-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s50-title.m4a",
        "thumb": "/help-guide/s50-0.jpg"
      }
    ]
  },
  {
    "id": "settings",
    "icon": "⚙️",
    "title": "إعدادات الكنيسة",
    "minRole": "super_admin",
    "titleEn": "Church Settings",
    "lessons": [
      {
        "id": "51",
        "icon": "⚙️",
        "title": "صفحة الإعدادات",
        "titleEn": "The Settings Page",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "🗂️",
            "ar": "أربع إعدادات: كود QR، الإشعارات، الخصوصية، والصلاحيات.",
            "en": "Four settings: QR code, notifications, privacy, and permissions.",
            "img": "/help-guide/s51-0.jpg",
            "vid": "/help-guide/v-s51-0.mp4",
            "aud": "/help-guide/a-s51-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s51-title.m4a",
        "thumb": "/help-guide/s51-0.jpg"
      },
      {
        "id": "52",
        "icon": "🛡️",
        "title": "الصلاحيات",
        "titleEn": "Permissions",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "🎚️",
            "ar": "من هنا بتحدد كل دور يقدر يعمل إيه.",
            "en": "From here you decide what each role can do.",
            "img": "/help-guide/s52-0.jpg",
            "vid": "/help-guide/v-s52-0.mp4",
            "aud": "/help-guide/a-s52-0.m4a"
          },
          {
            "icon": "👤",
            "ar": "وتقدر تدي شخص واحد صلاحية زيادة من ملفه.",
            "en": "And you can give one person an extra permission from their profile.",
            "img": "/help-guide/s52-1.jpg",
            "aud": "/help-guide/a-s52-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s52-title.m4a",
        "thumb": "/help-guide/s52-0.jpg"
      },
      {
        "id": "53",
        "icon": "🔒",
        "title": "خصوصية أرقام التليفونات",
        "titleEn": "Phone Number Privacy",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "👁️",
            "ar": "اختار مين يشوف أرقام تليفونات الأعضاء: الكل، القادة، أو المشرفين بس.",
            "en": "Choose who can see members' phone numbers: everyone, leaders, or admins only.",
            "img": "/help-guide/s53-0.jpg",
            "vid": "/help-guide/v-s53-0.mp4",
            "aud": "/help-guide/a-s53-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s53-title.m4a",
        "thumb": "/help-guide/s53-0.jpg"
      },
      {
        "id": "54",
        "icon": "💬",
        "title": "قنوات الإشعارات (واتساب)",
        "titleEn": "Notification Channels (WhatsApp)",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "🎚️",
            "ar": "المفتاح ده بيشغّل إشعارات الواتساب المدفوعة — والإشعارات المجانية شغالة دايمًا.",
            "en": "This switch turns on paid WhatsApp notifications — the free notifications are always on.",
            "img": "/help-guide/s54-0.jpg",
            "vid": "/help-guide/v-s54-0.mp4",
            "aud": "/help-guide/a-s54-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s54-title.m4a",
        "thumb": "/help-guide/s54-0.jpg"
      }
    ]
  },
  {
    "id": "ref",
    "icon": "📖",
    "title": "مرجع سريع",
    "minRole": "member",
    "titleEn": "Quick Reference",
    "lessons": [
      {
        "id": "55",
        "icon": "🏛️",
        "title": "موافقة الكنائس الجديدة (للمشغّل)",
        "titleEn": "Approving New Churches (for the Operator)",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "✅",
            "ar": "مشغّل المنصة بيراجع كل كنيسة جديدة ويتصل بصاحبها قبل التفعيل.",
            "en": "The platform operator reviews every new church and calls its owner before activation.",
            "img": "/help-guide/s55-0.jpg",
            "aud": "/help-guide/a-s55-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s55-title.m4a",
        "thumb": "/help-guide/s55-0.jpg"
      },
      {
        "id": "56",
        "icon": "📖",
        "title": "مرجع سريع: مين يقدر يعمل إيه",
        "titleEn": "Quick Reference: Who Can Do What",
        "minRole": "member",
        "steps": [
          {
            "icon": "ℹ️",
            "ar": "العضو بيشوف صفحاته، والقائد بيدير مجموعته، والمشرف بيدير كل حاجة.",
            "en": "A member sees their own pages, a leader manages their group, and an admin manages everything.",
            "img": "/help-guide/s56-0.jpg",
            "aud": "/help-guide/a-s56-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s56-title.m4a",
        "thumb": "/help-guide/s56-0.jpg"
      },
      {
        "id": "57",
        "icon": "⌨️",
        "title": "اختصارات ومميزات خفية",
        "titleEn": "Shortcuts and Hidden Features",
        "minRole": "member",
        "steps": [
          {
            "icon": "💡",
            "ar": "في شاشة العرض: الأسهم بتنقّل، وحرف F للشاشة الكاملة.",
            "en": "In the presenter: arrow keys move between slides, and F goes full screen.",
            "img": "/help-guide/s57-0.jpg",
            "aud": "/help-guide/a-s57-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s57-title.m4a",
        "thumb": "/help-guide/s57-0.jpg"
      },
      {
        "id": "58",
        "icon": "📏",
        "title": "حدود وإعدادات مهمة",
        "titleEn": "Important Limits and Settings",
        "minRole": "member",
        "steps": [
          {
            "icon": "ℹ️",
            "ar": "الصور أقصاها ٥ ميجا، وكلمة السر ٦ حروف على الأقل، ورقم التليفون لازم يبدأ بكود الدولة.",
            "en": "Photos are 5 MB max, passwords need at least 6 characters, and phone numbers must start with the country code.",
            "img": "/help-guide/s58-0.jpg",
            "aud": "/help-guide/a-s58-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s58-title.m4a",
        "thumb": "/help-guide/s58-0.jpg"
      },
      {
        "id": "59",
        "icon": "🩹",
        "title": "حل المشاكل الشائعة",
        "titleEn": "Fixing Common Problems",
        "minRole": "member",
        "steps": [
          {
            "icon": "❓",
            "ar": "لو حاجة مش شغالة: حدّث الصفحة، وتأكد من دورك، أو اسأل مشرف كنيستك.",
            "en": "If something isn't working: refresh the page, check your role, or ask your church admin.",
            "img": "/help-guide/s59-0.jpg",
            "aud": "/help-guide/a-s59-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s59-title.m4a",
        "thumb": "/help-guide/s59-0.jpg"
      }
    ]
  }
] as GuideCategory[]

export function findLesson(id: string): { lesson: GuideLesson; category: GuideCategory } | null {
  for (const c of GUIDE) { const l = c.lessons.find(x => x.id === id); if (l) return { lesson: l, category: c } }
  return null
}

// Longest-prefix route → lesson id (for the contextual Help button)
const PATH_LESSONS: [string, string][] = [["/admin/settings/qr","37"],["/admin/settings/roles","52"],["/admin/settings/privacy","53"],["/admin/settings/notifications","54"],["/admin/settings","51"],["/admin/members","33"],["/admin/visitors","36"],["/admin/groups","38"],["/admin/ministries","39"],["/admin/events","40"],["/admin/templates","41"],["/admin/calendar","42"],["/admin/prayers","45"],["/admin/songs","21"],["/admin/outreach","47"],["/admin/locations","48"],["/admin/join-requests","50"],["/my-group","26"],["/visitors","31"],["/groups","24"],["/events","15"],["/serving","16"],["/announcements","17"],["/prayer","18"],["/bible","19"],["/liturgy","20"],["/bookings","22"],["/community/needs","23"],["/notifications","14"],["/profile","13"],["/dashboard","12"]]
export function lessonIdForPath(pathname: string, role: UserRole): string | null {
  for (const [prefix, id] of PATH_LESSONS) {
    if (pathname === prefix || pathname.startsWith(prefix + '/')) {
      const hit = findLesson(id)
      if (hit && canSee(role, hit.lesson.minRole)) return id
    }
  }
  return null
}
