// AUTO-GENERATED by docs/visual-guide/gen-app-data.mjs — do not edit by hand.
// Content dataset for the in-app visual guide (Arabic, low-literacy audience).
import type { UserRole } from '@/types'

export interface GuideStep { icon: string; ar: string; img?: string; vid?: string; aud?: string }
export interface GuideLesson {
  id: string; icon: string; title: string; minRole: UserRole
  steps: GuideStep[]; titleAud?: string; thumb?: string
}
export interface GuideCategory {
  id: string; icon: string; title: string; minRole: UserRole; lessons: GuideLesson[]
}

const ROLE_RANK: Record<UserRole, number> = { member: 0, group_leader: 1, ministry_leader: 2, super_admin: 3 }
export const canSee = (role: UserRole, minRole: UserRole) => ROLE_RANK[role] >= ROLE_RANK[minRole]

export const GUIDE: GuideCategory[] = [
  {
    "id": "welcome",
    "icon": "👋",
    "title": "أهلًا بيك",
    "minRole": "member",
    "lessons": [
      {
        "id": "1",
        "icon": "⛪",
        "title": "ما هي إكليسيا؟",
        "minRole": "member",
        "steps": [
          {
            "icon": "👋",
            "ar": "دي الصفحة الرئيسية لتطبيق إكليسيا.",
            "img": "/help-guide/s1-0.jpg",
            "aud": "/help-guide/a-s1-0.m4a"
          },
          {
            "icon": "📜",
            "ar": "انزل تحت تشوف كل حاجة التطبيق بيعملها.",
            "img": "/help-guide/s1-1.jpg",
            "vid": "/help-guide/v-s1-1.mp4",
            "aud": "/help-guide/a-s1-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s1-title.m4a",
        "thumb": "/help-guide/s1-0.jpg"
      },
      {
        "id": "2",
        "icon": "👥",
        "title": "الأدوار الأربعة في التطبيق",
        "minRole": "member",
        "steps": [
          {
            "icon": "🧑‍🤝‍🧑",
            "ar": "كل شخص له دور: عضو، أو قائد مجموعة، أو قائد خدمة، أو مشرف.",
            "img": "/help-guide/s2-0.jpg",
            "aud": "/help-guide/a-s2-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s2-title.m4a",
        "thumb": "/help-guide/s2-0.jpg"
      }
    ]
  },
  {
    "id": "start",
    "icon": "🚪",
    "title": "أول خطوة",
    "minRole": "member",
    "lessons": [
      {
        "id": "3",
        "icon": "🏛️",
        "title": "تسجيل كنيستك (للرعاة)",
        "minRole": "member",
        "steps": [
          {
            "icon": "🚀",
            "ar": "اضغط زر \"هيا نبدأ\" علشان تبدأ تسجيل كنيستك.",
            "img": "/help-guide/s3-0.jpg",
            "vid": "/help-guide/v-s3-0.mp4",
            "aud": "/help-guide/a-s3-0.m4a"
          },
          {
            "icon": "✉️",
            "ar": "اكتب بريدك الإلكتروني هنا.",
            "img": "/help-guide/s3-1.jpg",
            "aud": "/help-guide/a-s3-1.m4a"
          },
          {
            "icon": "🔒",
            "ar": "اكتب كلمة سر جديدة، وبعدين اكتبها تاني للتأكيد.",
            "img": "/help-guide/s3-2.jpg",
            "aud": "/help-guide/a-s3-2.m4a"
          },
          {
            "icon": "🙍",
            "ar": "اكتب اسمك ورقم تليفونك علشان نتواصل معاك.",
            "img": "/help-guide/s3-3.jpg",
            "aud": "/help-guide/a-s3-3.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s3-title.m4a",
        "thumb": "/help-guide/s3-0.jpg"
      },
      {
        "id": "4",
        "icon": "📝",
        "title": "إنشاء حساب والانضمام لكنيستك",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔎",
            "ar": "اكتب اسم كنيستك في خانة البحث.",
            "img": "/help-guide/s4-0.jpg",
            "vid": "/help-guide/v-s4-0.mp4",
            "aud": "/help-guide/a-s4-0.m4a"
          },
          {
            "icon": "👆",
            "ar": "اختار كنيستك من القائمة اللي هتظهر.",
            "img": "/help-guide/s4-1.jpg",
            "aud": "/help-guide/a-s4-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s4-title.m4a",
        "thumb": "/help-guide/s4-0.jpg"
      },
      {
        "id": "5",
        "icon": "🔑",
        "title": "تسجيل الدخول",
        "minRole": "member",
        "steps": [
          {
            "icon": "✉️",
            "ar": "اكتب بريدك الإلكتروني هنا.",
            "img": "/help-guide/s5-0.jpg",
            "vid": "/help-guide/v-s5-0.mp4",
            "aud": "/help-guide/a-s5-0.m4a"
          },
          {
            "icon": "🔒",
            "ar": "اكتب كلمة السر بتاعتك.",
            "img": "/help-guide/s5-1.jpg",
            "aud": "/help-guide/a-s5-1.m4a"
          },
          {
            "icon": "👆",
            "ar": "اضغط زر \"دخول\".",
            "img": "/help-guide/s5-2.jpg",
            "vid": "/help-guide/v-s5-2.mp4",
            "aud": "/help-guide/a-s5-2.m4a"
          },
          {
            "icon": "🏠",
            "ar": "أهلًا بيك! دي صفحتك الرئيسية.",
            "img": "/help-guide/s5-3.jpg",
            "aud": "/help-guide/a-s5-3.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s5-title.m4a",
        "thumb": "/help-guide/s5-0.jpg"
      },
      {
        "id": "5b",
        "icon": "📱",
        "title": "الدخول برقم التليفون (واتساب)",
        "minRole": "member",
        "steps": [
          {
            "icon": "📲",
            "ar": "اضغط على تبويب \"الهاتف\".",
            "img": "/help-guide/s5b-0.jpg",
            "vid": "/help-guide/v-s5b-0.mp4",
            "aud": "/help-guide/a-s5b-0.m4a"
          },
          {
            "icon": "☎️",
            "ar": "اكتب رقم تليفونك بكود الدولة، زي +20 لمصر.",
            "img": "/help-guide/s5b-1.jpg",
            "aud": "/help-guide/a-s5b-1.m4a"
          },
          {
            "icon": "💬",
            "ar": "اضغط الزر ده، وهيوصلك كود من ٦ أرقام على واتساب.",
            "img": "/help-guide/s5b-2.jpg",
            "aud": "/help-guide/a-s5b-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s5b-title.m4a",
        "thumb": "/help-guide/s5b-0.jpg"
      },
      {
        "id": "6",
        "icon": "🆘",
        "title": "نسيت كلمة السر؟",
        "minRole": "member",
        "steps": [
          {
            "icon": "👆",
            "ar": "اضغط على \"هل نسيت كلمة المرور؟\".",
            "img": "/help-guide/s6-0.jpg",
            "vid": "/help-guide/v-s6-0.mp4",
            "aud": "/help-guide/a-s6-0.m4a"
          },
          {
            "icon": "✉️",
            "ar": "اكتب بريدك الإلكتروني.",
            "img": "/help-guide/s6-1.jpg",
            "aud": "/help-guide/a-s6-1.m4a"
          },
          {
            "icon": "📨",
            "ar": "اضغط \"إرسال رابط إعادة التعيين\" وافتح بريدك بعدها.",
            "img": "/help-guide/s6-2.jpg",
            "vid": "/help-guide/v-s6-2.mp4",
            "aud": "/help-guide/a-s6-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s6-title.m4a",
        "thumb": "/help-guide/s6-0.jpg"
      },
      {
        "id": "7",
        "icon": "🪪",
        "title": "إكمال ملفك أول مرة",
        "minRole": "member",
        "steps": [
          {
            "icon": "🖊️",
            "ar": "أول مرة تدخل، هتكتب اسمك بالعربي ورقم تليفونك هنا.",
            "img": "/help-guide/s7-0.jpg",
            "aud": "/help-guide/a-s7-0.m4a"
          },
          {
            "icon": "🔔",
            "ar": "اختار طريقة الإشعارات اللي تناسبك، وبعدين اضغط حفظ.",
            "img": "/help-guide/s7-1.jpg",
            "aud": "/help-guide/a-s7-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s7-title.m4a",
        "thumb": "/help-guide/s7-0.jpg"
      },
      {
        "id": "8",
        "icon": "🧭",
        "title": "التنقل داخل التطبيق",
        "minRole": "member",
        "steps": [
          {
            "icon": "📋",
            "ar": "القائمة الجانبية دي فيها كل صفحات التطبيق.",
            "img": "/help-guide/s8-0.jpg",
            "vid": "/help-guide/v-s8-0.mp4",
            "aud": "/help-guide/a-s8-0.m4a"
          },
          {
            "icon": "🔔",
            "ar": "الجرس ده بيوريك الإشعارات الجديدة.",
            "img": "/help-guide/s8-1.jpg",
            "aud": "/help-guide/a-s8-1.m4a"
          },
          {
            "icon": "🚪",
            "ar": "ومن هنا تقدر تسجل الخروج.",
            "img": "/help-guide/s8-2.jpg",
            "aud": "/help-guide/a-s8-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s8-title.m4a",
        "thumb": "/help-guide/s8-0.jpg"
      },
      {
        "id": "9",
        "icon": "🌐",
        "title": "التبديل بين العربية والإنجليزية",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔤",
            "ar": "اضغط على زر اللغة اللي فوق علشان تبدّل بين العربي والإنجليزي.",
            "img": "/help-guide/s9-0.jpg",
            "vid": "/help-guide/v-s9-0.mp4",
            "aud": "/help-guide/a-s9-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s9-title.m4a",
        "thumb": "/help-guide/s9-0.jpg"
      },
      {
        "id": "10",
        "icon": "🔕",
        "title": "تفعيل الإشعارات",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔔",
            "ar": "لما يظهرلك الكرت ده، اضغط \"تفعيل\" علشان توصلك الإشعارات على تليفونك.",
            "img": "/help-guide/s10-0.jpg",
            "aud": "/help-guide/a-s10-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s10-title.m4a",
        "thumb": "/help-guide/s10-0.jpg"
      },
      {
        "id": "11",
        "icon": "🏘️",
        "title": "أكثر من كنيسة بحساب واحد",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔁",
            "ar": "لو عندك أكتر من كنيسة، اضغط على اسم الكنيسة فوق علشان تبدّل بينهم.",
            "img": "/help-guide/s11-0.jpg",
            "aud": "/help-guide/a-s11-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s11-title.m4a",
        "thumb": "/help-guide/s11-0.jpg"
      }
    ]
  },
  {
    "id": "member",
    "icon": "🏠",
    "title": "للأعضاء",
    "minRole": "member",
    "lessons": [
      {
        "id": "12",
        "icon": "🏠",
        "title": "صفحتك الرئيسية",
        "minRole": "member",
        "steps": [
          {
            "icon": "📊",
            "ar": "هنا بتشوف حضورك ومجموعاتك وإشعاراتك.",
            "img": "/help-guide/s12-0.jpg",
            "vid": "/help-guide/v-s12-0.mp4",
            "aud": "/help-guide/a-s12-0.m4a"
          },
          {
            "icon": "📅",
            "ar": "وتحت هتلاقي الفعاليات الجاية وآخر الإعلانات.",
            "img": "/help-guide/s12-1.jpg",
            "vid": "/help-guide/v-s12-1.mp4",
            "aud": "/help-guide/a-s12-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s12-title.m4a",
        "thumb": "/help-guide/s12-0.jpg"
      },
      {
        "id": "13",
        "icon": "🪪",
        "title": "ملفك الشخصي",
        "minRole": "member",
        "steps": [
          {
            "icon": "👀",
            "ar": "ده ملفك الشخصي وفيه كل بياناتك.",
            "img": "/help-guide/s13-0.jpg",
            "vid": "/help-guide/v-s13-0.mp4",
            "aud": "/help-guide/a-s13-0.m4a"
          },
          {
            "icon": "✏️",
            "ar": "اضغط زر التعديل علشان تغيّر بياناتك أو صورتك.",
            "img": "/help-guide/s13-1.jpg",
            "vid": "/help-guide/v-s13-1.mp4",
            "aud": "/help-guide/a-s13-1.m4a"
          },
          {
            "icon": "📷",
            "ar": "من هنا تضيف أو تغيّر صورتك (أقصى حجم ٥ ميجا).",
            "img": "/help-guide/s13-2.jpg",
            "aud": "/help-guide/a-s13-2.m4a"
          },
          {
            "icon": "💾",
            "ar": "لما تخلص اضغط \"حفظ التغييرات\".",
            "img": "/help-guide/s13-3.jpg",
            "aud": "/help-guide/a-s13-3.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s13-title.m4a",
        "thumb": "/help-guide/s13-0.jpg"
      },
      {
        "id": "14",
        "icon": "🔔",
        "title": "الإشعارات",
        "minRole": "member",
        "steps": [
          {
            "icon": "📬",
            "ar": "هنا كل إشعاراتك، والجديد عليه علامة.",
            "img": "/help-guide/s14-0.jpg",
            "vid": "/help-guide/v-s14-0.mp4",
            "aud": "/help-guide/a-s14-0.m4a"
          },
          {
            "icon": "👆",
            "ar": "اضغط على أي إشعار علشان تشوف تفاصيله.",
            "img": "/help-guide/s14-1.jpg",
            "aud": "/help-guide/a-s14-1.m4a"
          },
          {
            "icon": "✅",
            "ar": "وزر \"تحديد الكل كمقروء\" بيمسح كل العلامات مرة واحدة.",
            "img": "/help-guide/s14-2.jpg",
            "aud": "/help-guide/a-s14-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s14-title.m4a",
        "thumb": "/help-guide/s14-0.jpg"
      },
      {
        "id": "15",
        "icon": "📅",
        "title": "الفعاليات والتسجيل فيها",
        "minRole": "member",
        "steps": [
          {
            "icon": "📋",
            "ar": "دي كل الفعاليات الجاية في كنيستك.",
            "img": "/help-guide/s15-0.jpg",
            "vid": "/help-guide/v-s15-0.mp4",
            "aud": "/help-guide/a-s15-0.m4a"
          },
          {
            "icon": "👆",
            "ar": "اضغط على أي فعالية تشوف تفاصيلها.",
            "img": "/help-guide/s15-1.jpg",
            "vid": "/help-guide/v-s15-1.mp4",
            "aud": "/help-guide/a-s15-1.m4a"
          },
          {
            "icon": "✍️",
            "ar": "لو فيه زر \"تسجيل\"، اضغطه علشان تحجز مكانك.",
            "img": "/help-guide/s15-2.jpg",
            "aud": "/help-guide/a-s15-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s15-title.m4a",
        "thumb": "/help-guide/s15-0.jpg"
      },
      {
        "id": "16",
        "icon": "🤝",
        "title": "الخدمة والتطوع",
        "minRole": "member",
        "steps": [
          {
            "icon": "📋",
            "ar": "دي أوقات الخدمة المتاحة للتطوع.",
            "img": "/help-guide/s16-0.jpg",
            "vid": "/help-guide/v-s16-0.mp4",
            "aud": "/help-guide/a-s16-0.m4a"
          },
          {
            "icon": "👆",
            "ar": "افتح أي وقت خدمة واضغط \"سجّل\" علشان تتطوع.",
            "img": "/help-guide/s16-1.jpg",
            "vid": "/help-guide/v-s16-1.mp4",
            "aud": "/help-guide/a-s16-1.m4a"
          },
          {
            "icon": "✅",
            "ar": "اشتراكاتك بتظهر تحت في \"اشتراكاتي\".",
            "img": "/help-guide/s16-2.jpg",
            "aud": "/help-guide/a-s16-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s16-title.m4a",
        "thumb": "/help-guide/s16-0.jpg"
      },
      {
        "id": "17",
        "icon": "📢",
        "title": "الإعلانات",
        "minRole": "member",
        "steps": [
          {
            "icon": "📰",
            "ar": "هنا آخر أخبار وإعلانات الكنيسة، والمثبّت بيظهر الأول.",
            "img": "/help-guide/s17-0.jpg",
            "vid": "/help-guide/v-s17-0.mp4",
            "aud": "/help-guide/a-s17-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s17-title.m4a",
        "thumb": "/help-guide/s17-0.jpg"
      },
      {
        "id": "18",
        "icon": "🙏",
        "title": "طلبات الصلاة",
        "minRole": "member",
        "steps": [
          {
            "icon": "✍️",
            "ar": "اكتب طلب صلاتك هنا.",
            "img": "/help-guide/s18-0.jpg",
            "vid": "/help-guide/v-s18-0.mp4",
            "aud": "/help-guide/a-s18-0.m4a"
          },
          {
            "icon": "👁️",
            "ar": "اختار مين يشوف طلبك: الكل، أو من غير اسمك، أو القادة بس.",
            "img": "/help-guide/s18-1.jpg",
            "aud": "/help-guide/a-s18-1.m4a"
          },
          {
            "icon": "📤",
            "ar": "اضغط \"إرسال الطلب\".",
            "img": "/help-guide/s18-2.jpg",
            "vid": "/help-guide/v-s18-2.mp4",
            "aud": "/help-guide/a-s18-2.m4a"
          },
          {
            "icon": "❤️",
            "ar": "واضغط \"أصلي\" على طلبات غيرك علشان تشجعهم.",
            "img": "/help-guide/s18-3.jpg",
            "vid": "/help-guide/v-s18-3.mp4",
            "aud": "/help-guide/a-s18-3.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s18-title.m4a",
        "thumb": "/help-guide/s18-0.jpg"
      },
      {
        "id": "19",
        "icon": "📖",
        "title": "قراءة الكتاب المقدس",
        "minRole": "member",
        "steps": [
          {
            "icon": "📚",
            "ar": "اضغط \"اختر سفرًا\" واختار السفر اللي عايز تقراه.",
            "img": "/help-guide/s19-0.jpg",
            "vid": "/help-guide/v-s19-0.mp4",
            "aud": "/help-guide/a-s19-0.m4a"
          },
          {
            "icon": "🔢",
            "ar": "وبعدين اختار الإصحاح.",
            "img": "/help-guide/s19-1.jpg",
            "vid": "/help-guide/v-s19-1.mp4",
            "aud": "/help-guide/a-s19-1.m4a"
          },
          {
            "icon": "🖍️",
            "ar": "اضغط على أي آية علشان تظللها أو تحفظها أو تنسخها.",
            "img": "/help-guide/s19-2.jpg",
            "vid": "/help-guide/v-s19-2.mp4",
            "aud": "/help-guide/a-s19-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s19-title.m4a",
        "thumb": "/help-guide/s19-0.jpg"
      },
      {
        "id": "20",
        "icon": "⛪",
        "title": "الأجبية والقراءات والألحان",
        "minRole": "member",
        "steps": [
          {
            "icon": "🕐",
            "ar": "من هنا تفتح الأجبية وقراءات اليوم والقداسات والألحان.",
            "img": "/help-guide/s20-0.jpg",
            "vid": "/help-guide/v-s20-0.mp4",
            "aud": "/help-guide/a-s20-0.m4a"
          },
          {
            "icon": "📿",
            "ar": "مثلًا اضغط \"الأجبية\" واختار الساعة اللي عايز تصليها.",
            "img": "/help-guide/s20-1.jpg",
            "vid": "/help-guide/v-s20-1.mp4",
            "aud": "/help-guide/a-s20-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s20-title.m4a",
        "thumb": "/help-guide/s20-0.jpg"
      },
      {
        "id": "21",
        "icon": "🎵",
        "title": "الترانيم",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔎",
            "ar": "دوّر على أي ترنيمة بالاسم أو بكلماتها.",
            "img": "/help-guide/s21-0.jpg",
            "vid": "/help-guide/v-s21-0.mp4",
            "aud": "/help-guide/a-s21-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s21-title.m4a",
        "thumb": "/help-guide/s21-0.jpg"
      },
      {
        "id": "22",
        "icon": "🚪",
        "title": "حجز قاعة",
        "minRole": "member",
        "steps": [
          {
            "icon": "🏢",
            "ar": "اختار القاعة واليوم، وشوف المواعيد الفاضية.",
            "img": "/help-guide/s22-0.jpg",
            "vid": "/help-guide/v-s22-0.mp4",
            "aud": "/help-guide/a-s22-0.m4a"
          },
          {
            "icon": "➕",
            "ar": "اضغط زر الحجز واكتب عنوان ووقت حجزك.",
            "img": "/help-guide/s22-1.jpg",
            "vid": "/help-guide/v-s22-1.mp4",
            "aud": "/help-guide/a-s22-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s22-title.m4a",
        "thumb": "/help-guide/s22-0.jpg"
      },
      {
        "id": "23",
        "icon": "🤲",
        "title": "احتياجات الكنائس",
        "minRole": "member",
        "steps": [
          {
            "icon": "📋",
            "ar": "هنا كنائس تانية بتطلب مساعدة، وتقدر تساعدهم.",
            "img": "/help-guide/s23-0.jpg",
            "vid": "/help-guide/v-s23-0.mp4",
            "aud": "/help-guide/a-s23-0.m4a"
          },
          {
            "icon": "💌",
            "ar": "افتح أي احتياج واضغط \"قدّم مساعدة\" واكتب رسالتك.",
            "img": "/help-guide/s23-1.jpg",
            "aud": "/help-guide/a-s23-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s23-title.m4a",
        "thumb": "/help-guide/s23-0.jpg"
      },
      {
        "id": "24",
        "icon": "👨‍👩‍👧",
        "title": "المجموعات والانضمام ليها",
        "minRole": "member",
        "steps": [
          {
            "icon": "🔎",
            "ar": "من صفحة المجموعات تشوف مجموعاتك والمجموعات المفتوحة.",
            "img": "/help-guide/s24-0.jpg",
            "aud": "/help-guide/a-s24-0.m4a"
          },
          {
            "icon": "✋",
            "ar": "اضغط \"اطلب الانضمام\" والقائد هيوافق عليك.",
            "img": "/help-guide/s24-1.jpg",
            "aud": "/help-guide/a-s24-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s24-title.m4a",
        "thumb": "/help-guide/s24-0.jpg"
      },
      {
        "id": "25",
        "icon": "💌",
        "title": "دعوات الكنائس",
        "minRole": "member",
        "steps": [
          {
            "icon": "✅",
            "ar": "لو كنيسة دعتك، هيظهر كرت على صفحتك: اقبل أو ارفض.",
            "img": "/help-guide/s25-0.jpg",
            "aud": "/help-guide/a-s25-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s25-title.m4a",
        "thumb": "/help-guide/s25-0.jpg"
      }
    ]
  },
  {
    "id": "leader",
    "icon": "👨‍👩‍👧‍👦",
    "title": "لقائد المجموعة",
    "minRole": "group_leader",
    "lessons": [
      {
        "id": "26",
        "icon": "👨‍👩‍👧‍👦",
        "title": "صفحة مجموعتي (للقائد)",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "📊",
            "ar": "دي صفحة مجموعتك: الأعضاء والحضور والاجتماعات.",
            "img": "/help-guide/s26-0.jpg",
            "vid": "/help-guide/v-s26-0.mp4",
            "aud": "/help-guide/a-s26-0.m4a"
          },
          {
            "icon": "⚠️",
            "ar": "وهنا الأعضاء اللي غابوا كتير ومحتاجين افتقاد.",
            "img": "/help-guide/s26-1.jpg",
            "aud": "/help-guide/a-s26-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s26-title.m4a",
        "thumb": "/help-guide/s26-0.jpg"
      },
      {
        "id": "27",
        "icon": "🗓️",
        "title": "إنشاء اجتماع جديد",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "🕐",
            "ar": "حدد يوم وساعة الاجتماع.",
            "img": "/help-guide/s27-0.jpg",
            "vid": "/help-guide/v-s27-0.mp4",
            "aud": "/help-guide/a-s27-0.m4a"
          },
          {
            "icon": "📝",
            "ar": "اكتب موضوع الاجتماع ومكانه.",
            "img": "/help-guide/s27-1.jpg",
            "vid": "/help-guide/v-s27-1.mp4",
            "aud": "/help-guide/a-s27-1.m4a"
          },
          {
            "icon": "✅",
            "ar": "اضغط \"إنشاء الاجتماع\".",
            "img": "/help-guide/s27-2.jpg",
            "vid": "/help-guide/v-s27-2.mp4",
            "aud": "/help-guide/a-s27-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s27-title.m4a",
        "thumb": "/help-guide/s27-0.jpg"
      },
      {
        "id": "28",
        "icon": "✅",
        "title": "تسجيل الحضور",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "👆",
            "ar": "اضغط على اسم أي عضو علشان تغيّر حالته: حاضر، متأخر، غايب.",
            "img": "/help-guide/s28-0.jpg",
            "vid": "/help-guide/v-s28-0.mp4",
            "aud": "/help-guide/a-s28-0.m4a"
          },
          {
            "icon": "💾",
            "ar": "اضغط \"حفظ الحضور\" في أي وقت.",
            "img": "/help-guide/s28-1.jpg",
            "vid": "/help-guide/v-s28-1.mp4",
            "aud": "/help-guide/a-s28-1.m4a"
          },
          {
            "icon": "🏁",
            "ar": "ولما الاجتماع يخلص، اضغط \"إنهاء الاجتماع\".",
            "img": "/help-guide/s28-2.jpg",
            "vid": "/help-guide/v-s28-2.mp4",
            "aud": "/help-guide/a-s28-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s28-title.m4a",
        "thumb": "/help-guide/s28-0.jpg"
      },
      {
        "id": "29",
        "icon": "🙏",
        "title": "صلوات المجموعة وتسجيل الاستجابات",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "➕",
            "ar": "من قسم الصلاة اضغط \"أضف طلبًا\" واكتب الطلب.",
            "img": "/help-guide/s29-0.jpg",
            "aud": "/help-guide/a-s29-0.m4a"
          },
          {
            "icon": "🎉",
            "ar": "ولما ربنا يستجيب، اضغط \"سجّل الاستجابة\".",
            "img": "/help-guide/s29-1.jpg",
            "aud": "/help-guide/a-s29-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s29-title.m4a",
        "thumb": "/help-guide/s29-0.jpg"
      },
      {
        "id": "30",
        "icon": "✋",
        "title": "الموافقة على طلبات الانضمام للمجموعة",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "✅",
            "ar": "طلبات الانضمام بتظهر في صفحة مجموعتك: اضغط \"موافقة\" أو \"رفض\".",
            "img": "/help-guide/s30-0.jpg",
            "aud": "/help-guide/a-s30-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s30-title.m4a",
        "thumb": "/help-guide/s30-0.jpg"
      },
      {
        "id": "31",
        "icon": "📞",
        "title": "الزوار المسندين ليك",
        "minRole": "group_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "دول الزوار اللي الكنيسة كلفتك تتابعهم.",
            "img": "/help-guide/s31-0.jpg",
            "vid": "/help-guide/v-s31-0.mp4",
            "aud": "/help-guide/a-s31-0.m4a"
          },
          {
            "icon": "📞",
            "ar": "اتصل بيهم، وبعدين اضغط \"سجّل تواصل\" واكتب اللي حصل.",
            "img": "/help-guide/s31-1.jpg",
            "vid": "/help-guide/v-s31-1.mp4",
            "aud": "/help-guide/a-s31-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s31-title.m4a",
        "thumb": "/help-guide/s31-0.jpg"
      }
    ]
  },
  {
    "id": "admin",
    "icon": "🛠️",
    "title": "للمشرفين والقادة",
    "minRole": "ministry_leader",
    "lessons": [
      {
        "id": "32",
        "icon": "📊",
        "title": "لوحة تحكم المشرف",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📈",
            "ar": "دي صحة كنيستك كلها في صفحة واحدة: الأعضاء والزوار والحضور.",
            "img": "/help-guide/s32-0.jpg",
            "vid": "/help-guide/v-s32-0.mp4",
            "aud": "/help-guide/a-s32-0.m4a"
          },
          {
            "icon": "⚠️",
            "ar": "قسم \"يحتاج انتباه\" بيوريك اللي لازم تتابعه النهارده.",
            "img": "/help-guide/s32-1.jpg",
            "aud": "/help-guide/a-s32-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s32-title.m4a",
        "thumb": "/help-guide/s32-0.jpg"
      },
      {
        "id": "33",
        "icon": "📇",
        "title": "دليل الأعضاء",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "ده دليل كل أعضاء الكنيسة.",
            "img": "/help-guide/s33-0.jpg",
            "vid": "/help-guide/v-s33-0.mp4",
            "aud": "/help-guide/a-s33-0.m4a"
          },
          {
            "icon": "🔎",
            "ar": "اكتب أي اسم في البحث والنتايج هتظهر فورًا.",
            "img": "/help-guide/s33-1.jpg",
            "vid": "/help-guide/v-s33-1.mp4",
            "aud": "/help-guide/a-s33-1.m4a"
          },
          {
            "icon": "👆",
            "ar": "اضغط على أي عضو تفتح ملفه.",
            "img": "/help-guide/s33-2.jpg",
            "vid": "/help-guide/v-s33-2.mp4",
            "aud": "/help-guide/a-s33-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s33-title.m4a",
        "thumb": "/help-guide/s33-0.jpg"
      },
      {
        "id": "34",
        "icon": "➕",
        "title": "إضافة عضو جديد",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "👆",
            "ar": "اضغط زر \"إضافة عضو\".",
            "img": "/help-guide/s34-0.jpg",
            "vid": "/help-guide/v-s34-0.mp4",
            "aud": "/help-guide/a-s34-0.m4a"
          },
          {
            "icon": "🖊️",
            "ar": "اكتب اسمه ورقم تليفونه.",
            "img": "/help-guide/s34-1.jpg",
            "aud": "/help-guide/a-s34-1.m4a"
          },
          {
            "icon": "✅",
            "ar": "اضغط \"إضافة عضو\" — وهو هيقدر يدخل بالواتساب على طول.",
            "img": "/help-guide/s34-2.jpg",
            "vid": "/help-guide/v-s34-2.mp4",
            "aud": "/help-guide/a-s34-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s34-title.m4a",
        "thumb": "/help-guide/s34-0.jpg"
      },
      {
        "id": "35",
        "icon": "🗂️",
        "title": "إدارة ملف عضو",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📑",
            "ar": "ملف العضو فيه بياناته ومحطاته الروحية ومشاركاته.",
            "img": "/help-guide/s35-0.jpg",
            "vid": "/help-guide/v-s35-0.mp4",
            "aud": "/help-guide/a-s35-0.m4a"
          },
          {
            "icon": "⚙️",
            "ar": "من تبويب \"إدارة\" تقدر تغيّر دوره وصلاحياته.",
            "img": "/help-guide/s35-1.jpg",
            "vid": "/help-guide/v-s35-1.mp4",
            "aud": "/help-guide/a-s35-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s35-title.m4a",
        "thumb": "/help-guide/s35-0.jpg"
      },
      {
        "id": "36",
        "icon": "🚶",
        "title": "قائمة الزوار ومتابعتهم",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "كل زائر جديد بيظهر هنا، والمتأخر عليه تنبيه أحمر.",
            "img": "/help-guide/s36-0.jpg",
            "vid": "/help-guide/v-s36-0.mp4",
            "aud": "/help-guide/a-s36-0.m4a"
          },
          {
            "icon": "🤝",
            "ar": "اضغط \"إسناد\" واختار قائد يتابع الزائر.",
            "img": "/help-guide/s36-1.jpg",
            "vid": "/help-guide/v-s36-1.mp4",
            "aud": "/help-guide/a-s36-1.m4a"
          },
          {
            "icon": "🎉",
            "ar": "ولما يبقى جاهز، اضغط \"تحويل لعضو\".",
            "img": "/help-guide/s36-2.jpg",
            "aud": "/help-guide/a-s36-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s36-title.m4a",
        "thumb": "/help-guide/s36-0.jpg"
      },
      {
        "id": "37",
        "icon": "📱",
        "title": "كود QR للزوار",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "🖨️",
            "ar": "اطبع الكود ده وحطه على باب الكنيسة.",
            "img": "/help-guide/s37-0.jpg",
            "vid": "/help-guide/v-s37-0.mp4",
            "aud": "/help-guide/a-s37-0.m4a"
          },
          {
            "icon": "⬇️",
            "ar": "زر \"تحميل PNG\" بينزّل الصورة للطباعة.",
            "img": "/help-guide/s37-1.jpg",
            "aud": "/help-guide/a-s37-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s37-title.m4a",
        "thumb": "/help-guide/s37-0.jpg"
      },
      {
        "id": "38",
        "icon": "👨‍👩‍👧‍👦",
        "title": "إدارة المجموعات",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "دي كل مجموعات الكنيسة.",
            "img": "/help-guide/s38-0.jpg",
            "vid": "/help-guide/v-s38-0.mp4",
            "aud": "/help-guide/a-s38-0.m4a"
          },
          {
            "icon": "➕",
            "ar": "اضغط \"مجموعة جديدة\" علشان تنشئ واحدة.",
            "img": "/help-guide/s38-1.jpg",
            "vid": "/help-guide/v-s38-1.mp4",
            "aud": "/help-guide/a-s38-1.m4a"
          },
          {
            "icon": "🖊️",
            "ar": "اكتب اسم المجموعة واختار القائد ويوم الاجتماع.",
            "img": "/help-guide/s38-2.jpg",
            "aud": "/help-guide/a-s38-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s38-title.m4a",
        "thumb": "/help-guide/s38-0.jpg"
      },
      {
        "id": "39",
        "icon": "🛠️",
        "title": "إدارة الخدمات (الوزارات)",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "دي كل خدمات الكنيسة، واضغط على أي خدمة تشوف فريقها.",
            "img": "/help-guide/s39-0.jpg",
            "vid": "/help-guide/v-s39-0.mp4",
            "aud": "/help-guide/a-s39-0.m4a"
          },
          {
            "icon": "➕",
            "ar": "زر \"إضافة خدمة\" بينشئ خدمة جديدة باسم وقائد.",
            "img": "/help-guide/s39-1.jpg",
            "aud": "/help-guide/a-s39-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s39-title.m4a",
        "thumb": "/help-guide/s39-0.jpg"
      },
      {
        "id": "40",
        "icon": "🎪",
        "title": "إنشاء فعالية (٧ خطوات)",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "🖊️",
            "ar": "الخطوة ١: اكتب اسم الفعالية واختار نوعها.",
            "img": "/help-guide/s40-0.jpg",
            "vid": "/help-guide/v-s40-0.mp4",
            "aud": "/help-guide/a-s40-0.m4a"
          },
          {
            "icon": "🕐",
            "ar": "الخطوة ٢: حدد التاريخ والساعة.",
            "img": "/help-guide/s40-1.jpg",
            "vid": "/help-guide/v-s40-1.mp4",
            "aud": "/help-guide/a-s40-1.m4a"
          },
          {
            "icon": "📍",
            "ar": "الخطوة ٣: اكتب المكان.",
            "img": "/help-guide/s40-2.jpg",
            "vid": "/help-guide/v-s40-2.mp4",
            "aud": "/help-guide/a-s40-2.m4a"
          },
          {
            "icon": "⚙️",
            "ar": "الخطوة ٤: فعّل \"التسجيل مطلوب\" لو عايز الناس تحجز.",
            "img": "/help-guide/s40-3.jpg",
            "vid": "/help-guide/v-s40-3.mp4",
            "aud": "/help-guide/a-s40-3.m4a"
          },
          {
            "icon": "👥",
            "ar": "الخطوة ٥: اختار مين يشوف الفعالية.",
            "img": "/help-guide/s40-4.jpg",
            "vid": "/help-guide/v-s40-4.mp4",
            "aud": "/help-guide/a-s40-4.m4a"
          },
          {
            "icon": "🤝",
            "ar": "الخطوة ٦: اطلب فرق خدمة لو محتاج متطوعين.",
            "img": "/help-guide/s40-5.jpg",
            "vid": "/help-guide/v-s40-5.mp4",
            "aud": "/help-guide/a-s40-5.m4a"
          },
          {
            "icon": "✅",
            "ar": "الخطوة ٧: راجع كل حاجة واضغط \"إنشاء الفعالية\".",
            "img": "/help-guide/s40-6.jpg",
            "vid": "/help-guide/v-s40-6.mp4",
            "aud": "/help-guide/a-s40-6.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s40-title.m4a",
        "thumb": "/help-guide/s40-0.jpg"
      },
      {
        "id": "41",
        "icon": "📋",
        "title": "قوالب الفعاليات",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "♻️",
            "ar": "اعمل قالب لقداس الأحد مرة واحدة، واستخدمه كل أسبوع.",
            "img": "/help-guide/s41-0.jpg",
            "vid": "/help-guide/v-s41-0.mp4",
            "aud": "/help-guide/a-s41-0.m4a"
          },
          {
            "icon": "▶️",
            "ar": "من صفحة الفعاليات اضغط \"من قالب\" وهيتعبى كل حاجة لوحده.",
            "img": "/help-guide/s41-1.jpg",
            "aud": "/help-guide/a-s41-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s41-title.m4a",
        "thumb": "/help-guide/s41-0.jpg"
      },
      {
        "id": "42",
        "icon": "🗓️",
        "title": "تقويم الكنيسة",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📅",
            "ar": "كل الفعاليات والخدمة والاجتماعات في تقويم واحد ملوّن.",
            "img": "/help-guide/s42-0.jpg",
            "vid": "/help-guide/v-s42-0.mp4",
            "aud": "/help-guide/a-s42-0.m4a"
          },
          {
            "icon": "🎚️",
            "ar": "الأزرار دي بتظهر وتخفي كل نوع.",
            "img": "/help-guide/s42-1.jpg",
            "aud": "/help-guide/a-s42-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s42-title.m4a",
        "thumb": "/help-guide/s42-0.jpg"
      },
      {
        "id": "43",
        "icon": "🧹",
        "title": "إدارة أماكن وأوقات الخدمة",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "من تبويب \"أماكن الخدمة\" اعمل فرق زي الاستقبال والصوت.",
            "img": "/help-guide/s43-0.jpg",
            "vid": "/help-guide/v-s43-0.mp4",
            "aud": "/help-guide/a-s43-0.m4a"
          },
          {
            "icon": "🕐",
            "ar": "ومن \"أوقات الخدمة\" حدد المواعيد اللي الناس تسجل فيها.",
            "img": "/help-guide/s43-1.jpg",
            "vid": "/help-guide/v-s43-1.mp4",
            "aud": "/help-guide/a-s43-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s43-title.m4a",
        "thumb": "/help-guide/s43-0.jpg"
      },
      {
        "id": "44",
        "icon": "📢",
        "title": "إدارة الإعلانات",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "➕",
            "ar": "اضغط \"إعلان جديد\".",
            "img": "/help-guide/s44-0.jpg",
            "vid": "/help-guide/v-s44-0.mp4",
            "aud": "/help-guide/a-s44-0.m4a"
          },
          {
            "icon": "🖊️",
            "ar": "اكتب العنوان والمحتوى.",
            "img": "/help-guide/s44-1.jpg",
            "aud": "/help-guide/a-s44-1.m4a"
          },
          {
            "icon": "📌",
            "ar": "فعّل \"تثبيت\" للإعلانات المهمة، وبعدين انشر.",
            "img": "/help-guide/s44-2.jpg",
            "vid": "/help-guide/v-s44-2.mp4",
            "aud": "/help-guide/a-s44-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s44-title.m4a",
        "thumb": "/help-guide/s44-0.jpg"
      },
      {
        "id": "45",
        "icon": "🙏",
        "title": "إدارة طلبات الصلاة",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "كل طلبات الصلاة هنا: نشطة، ومستجابة، ومؤرشفة.",
            "img": "/help-guide/s45-0.jpg",
            "vid": "/help-guide/v-s45-0.mp4",
            "aud": "/help-guide/a-s45-0.m4a"
          },
          {
            "icon": "🤝",
            "ar": "زر \"إسناد\" بيخلّي حد معيّن يصلي ويتابع الطلب.",
            "img": "/help-guide/s45-1.jpg",
            "aud": "/help-guide/a-s45-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s45-title.m4a",
        "thumb": "/help-guide/s45-0.jpg"
      },
      {
        "id": "46",
        "icon": "🎵",
        "title": "إدارة الترانيم والعرض",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "➕",
            "ar": "زر \"إضافة ترنيمة\": الاسم، الكلمات، وسطر فاضي بين كل شريحة.",
            "img": "/help-guide/s46-0.jpg",
            "vid": "/help-guide/v-s46-0.mp4",
            "aud": "/help-guide/a-s46-0.m4a"
          },
          {
            "icon": "📽️",
            "ar": "وزر \"عرض\" بيفتح شاشة العرض للبروجيكتور.",
            "img": "/help-guide/s46-1.jpg",
            "aud": "/help-guide/a-s46-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s46-title.m4a",
        "thumb": "/help-guide/s46-0.jpg"
      },
      {
        "id": "47",
        "icon": "🏡",
        "title": "الافتقاد والزيارات",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "📋",
            "ar": "هنا بتتابع مين اتزار في بيته ومين محتاج زيارة.",
            "img": "/help-guide/s47-0.jpg",
            "vid": "/help-guide/v-s47-0.mp4",
            "aud": "/help-guide/a-s47-0.m4a"
          },
          {
            "icon": "📝",
            "ar": "بعد كل زيارة اضغط \"سجّل زيارة\" واكتب اللي حصل.",
            "img": "/help-guide/s47-1.jpg",
            "aud": "/help-guide/a-s47-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s47-title.m4a",
        "thumb": "/help-guide/s47-0.jpg"
      },
      {
        "id": "48",
        "icon": "🏢",
        "title": "إدارة القاعات",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "➕",
            "ar": "ضيف قاعات كنيستك علشان الناس تقدر تحجزها.",
            "img": "/help-guide/s48-0.jpg",
            "vid": "/help-guide/v-s48-0.mp4",
            "aud": "/help-guide/a-s48-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s48-title.m4a",
        "thumb": "/help-guide/s48-0.jpg"
      },
      {
        "id": "49",
        "icon": "📣",
        "title": "إرسال إشعار لكل الكنيسة",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "🎯",
            "ar": "اختار مين يستلم: الكل، أو مجموعة، أو خدمة معينة.",
            "img": "/help-guide/s49-0.jpg",
            "vid": "/help-guide/v-s49-0.mp4",
            "aud": "/help-guide/a-s49-0.m4a"
          },
          {
            "icon": "🖊️",
            "ar": "اكتب العنوان والرسالة، وشوف عدد اللي هيوصلهم.",
            "img": "/help-guide/s49-1.jpg",
            "aud": "/help-guide/a-s49-1.m4a"
          },
          {
            "icon": "📤",
            "ar": "اضغط \"إرسال الإشعار\" وأكّد.",
            "img": "/help-guide/s49-2.jpg",
            "aud": "/help-guide/a-s49-2.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s49-title.m4a",
        "thumb": "/help-guide/s49-0.jpg"
      },
      {
        "id": "50",
        "icon": "✋",
        "title": "الموافقة على طلبات الانضمام للكنيسة",
        "minRole": "ministry_leader",
        "steps": [
          {
            "icon": "✅",
            "ar": "اللي طلب ينضم لكنيستك بيظهر هنا: اضغط \"موافقة\" أو \"رفض\".",
            "img": "/help-guide/s50-0.jpg",
            "vid": "/help-guide/v-s50-0.mp4",
            "aud": "/help-guide/a-s50-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s50-title.m4a",
        "thumb": "/help-guide/s50-0.jpg"
      }
    ]
  },
  {
    "id": "settings",
    "icon": "⚙️",
    "title": "إعدادات الكنيسة",
    "minRole": "super_admin",
    "lessons": [
      {
        "id": "51",
        "icon": "⚙️",
        "title": "صفحة الإعدادات",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "🗂️",
            "ar": "أربع إعدادات: كود QR، الإشعارات، الخصوصية، والصلاحيات.",
            "img": "/help-guide/s51-0.jpg",
            "vid": "/help-guide/v-s51-0.mp4",
            "aud": "/help-guide/a-s51-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s51-title.m4a",
        "thumb": "/help-guide/s51-0.jpg"
      },
      {
        "id": "52",
        "icon": "🛡️",
        "title": "الصلاحيات",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "🎚️",
            "ar": "من هنا بتحدد كل دور يقدر يعمل إيه.",
            "img": "/help-guide/s52-0.jpg",
            "vid": "/help-guide/v-s52-0.mp4",
            "aud": "/help-guide/a-s52-0.m4a"
          },
          {
            "icon": "👤",
            "ar": "وتقدر تدي شخص واحد صلاحية زيادة من ملفه.",
            "img": "/help-guide/s52-1.jpg",
            "aud": "/help-guide/a-s52-1.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s52-title.m4a",
        "thumb": "/help-guide/s52-0.jpg"
      },
      {
        "id": "53",
        "icon": "🔒",
        "title": "خصوصية أرقام التليفونات",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "👁️",
            "ar": "اختار مين يشوف أرقام تليفونات الأعضاء: الكل، القادة، أو المشرفين بس.",
            "img": "/help-guide/s53-0.jpg",
            "vid": "/help-guide/v-s53-0.mp4",
            "aud": "/help-guide/a-s53-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s53-title.m4a",
        "thumb": "/help-guide/s53-0.jpg"
      },
      {
        "id": "54",
        "icon": "💬",
        "title": "قنوات الإشعارات (واتساب)",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "🎚️",
            "ar": "المفتاح ده بيشغّل إشعارات الواتساب المدفوعة — والإشعارات المجانية شغالة دايمًا.",
            "img": "/help-guide/s54-0.jpg",
            "vid": "/help-guide/v-s54-0.mp4",
            "aud": "/help-guide/a-s54-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s54-title.m4a",
        "thumb": "/help-guide/s54-0.jpg"
      }
    ]
  },
  {
    "id": "ref",
    "icon": "📖",
    "title": "مرجع سريع",
    "minRole": "member",
    "lessons": [
      {
        "id": "55",
        "icon": "🏛️",
        "title": "موافقة الكنائس الجديدة (للمشغّل)",
        "minRole": "super_admin",
        "steps": [
          {
            "icon": "✅",
            "ar": "مشغّل المنصة بيراجع كل كنيسة جديدة ويتصل بصاحبها قبل التفعيل.",
            "img": "/help-guide/s55-0.jpg",
            "aud": "/help-guide/a-s55-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s55-title.m4a",
        "thumb": "/help-guide/s55-0.jpg"
      },
      {
        "id": "56",
        "icon": "📖",
        "title": "مرجع سريع: مين يقدر يعمل إيه",
        "minRole": "member",
        "steps": [
          {
            "icon": "ℹ️",
            "ar": "العضو بيشوف صفحاته، والقائد بيدير مجموعته، والمشرف بيدير كل حاجة.",
            "img": "/help-guide/s56-0.jpg",
            "aud": "/help-guide/a-s56-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s56-title.m4a",
        "thumb": "/help-guide/s56-0.jpg"
      },
      {
        "id": "57",
        "icon": "⌨️",
        "title": "اختصارات ومميزات خفية",
        "minRole": "member",
        "steps": [
          {
            "icon": "💡",
            "ar": "في شاشة العرض: الأسهم بتنقّل، وحرف F للشاشة الكاملة.",
            "img": "/help-guide/s57-0.jpg",
            "aud": "/help-guide/a-s57-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s57-title.m4a",
        "thumb": "/help-guide/s57-0.jpg"
      },
      {
        "id": "58",
        "icon": "📏",
        "title": "حدود وإعدادات مهمة",
        "minRole": "member",
        "steps": [
          {
            "icon": "ℹ️",
            "ar": "الصور أقصاها ٥ ميجا، وكلمة السر ٦ حروف على الأقل، ورقم التليفون لازم يبدأ بكود الدولة.",
            "img": "/help-guide/s58-0.jpg",
            "aud": "/help-guide/a-s58-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s58-title.m4a",
        "thumb": "/help-guide/s58-0.jpg"
      },
      {
        "id": "59",
        "icon": "🩹",
        "title": "حل المشاكل الشائعة",
        "minRole": "member",
        "steps": [
          {
            "icon": "❓",
            "ar": "لو حاجة مش شغالة: حدّث الصفحة، وتأكد من دورك، أو اسأل مشرف كنيستك.",
            "img": "/help-guide/s59-0.jpg",
            "aud": "/help-guide/a-s59-0.m4a"
          }
        ],
        "titleAud": "/help-guide/a-s59-title.m4a",
        "thumb": "/help-guide/s59-0.jpg"
      }
    ]
  }
] as GuideCategory[]

export function findLesson(id: string): { lesson: GuideLesson; category: GuideCategory } | null {
  for (const c of GUIDE) { const l = c.lessons.find(x => x.id === id); if (l) return { lesson: l, category: c } }
  return null
}

// Longest-prefix route → lesson id (for the contextual Help button)
const PATH_LESSONS: [string, string][] = [["/admin/settings/qr","37"],["/admin/settings/roles","52"],["/admin/settings/privacy","53"],["/admin/settings/notifications","54"],["/admin/settings","51"],["/admin/members","33"],["/admin/visitors","36"],["/admin/groups","38"],["/admin/ministries","39"],["/admin/events","40"],["/admin/templates","41"],["/admin/calendar","42"],["/admin/prayers","45"],["/admin/songs","21"],["/admin/outreach","47"],["/admin/locations","48"],["/admin/join-requests","50"],["/my-group","26"],["/visitors","31"],["/groups","24"],["/events","15"],["/serving","16"],["/announcements","17"],["/prayer","18"],["/bible","19"],["/liturgy","20"],["/bookings","22"],["/community/needs","23"],["/notifications","14"],["/profile","13"],["/dashboard","12"]]
export function lessonIdForPath(pathname: string, role: UserRole): string | null {
  for (const [prefix, id] of PATH_LESSONS) {
    if (pathname === prefix || pathname.startsWith(prefix + '/')) {
      const hit = findLesson(id)
      if (hit && canSee(role, hit.lesson.minRole)) return id
    }
  }
  return null
}
